{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>A vulnerability has been discovered and fixed in Mesop that could potentially allow unauthorized access to files on the server hosting the Mesop application. The vulnerability was related to insufficient input validation in a specific endpoint. This could have allowed an attacker to access files not intended to be served.</p>\n<p>Users are strongly advised to update to the latest version of Mesop immediately. The latest version includes a fix for this vulnerability.</p>\n<p>We would like to thank @Letm3through for reporting this issue and proposing mitigations to address this issue.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/google/mesop/security/advisories/GHSA-pmv9-3xqp-8w42\">https://github.com/google/mesop/security/advisories/GHSA-pmv9-3xqp-8w42</a></li>\n<li><a href=\"https://github.com/google/mesop/commit/17fb769d6a91f0a8cbccfab18f64977b158a6a31\">https://github.com/google/mesop/commit/17fb769d6a91f0a8cbccfab18f64977b158a6a31</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pmv9-3xqp-8w42\">https://github.com/advisories/GHSA-pmv9-3xqp-8w42</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pmv9-3xqp-8w42",
            "title": "[mesop] Mesop has a local file Inclusion via static file serving functionality",
            "date_modified": "2024-09-18T17:49:04.000Z",
            "date_published": "2024-09-18T17:49:02.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pmv9-3xqp-8w42"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An arbitrary code execution vulnerability exists in versions 0.2.9 up to 0.5.10 of the Guardrails AI Guardrails framework because of the way it validates XML files. If a victim user loads a maliciously crafted XML file containing Python code, the code will be passed to an eval function, causing it to execute on the user's machine.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-45858\">https://nvd.nist.gov/vuln/detail/CVE-2024-45858</a></li>\n<li><a href=\"https://hiddenlayer.com/sai-security-advisory/2024-09-guardrails\">https://hiddenlayer.com/sai-security-advisory/2024-09-guardrails</a></li>\n<li><a href=\"https://github.com/guardrails-ai/guardrails/commit/ab12701e8c3ef41273ff9b3912f2e4e28ae8306f\">https://github.com/guardrails-ai/guardrails/commit/ab12701e8c3ef41273ff9b3912f2e4e28ae8306f</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-w392-75q8-vr67\">https://github.com/advisories/GHSA-w392-75q8-vr67</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-w392-75q8-vr67",
            "title": "[guardrails-ai] Guardrails has an arbitrary code execution vulnerability",
            "date_modified": "2024-09-18T17:39:33.000Z",
            "date_published": "2024-09-18T15:30:52.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-w392-75q8-vr67"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Insecure deserialization in sqlitedict up to v2.1.0 allows attackers to execute arbitrary code.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-35515\">https://nvd.nist.gov/vuln/detail/CVE-2024-35515</a></li>\n<li><a href=\"https://github.com/piskvorky/sqlitedict\">https://github.com/piskvorky/sqlitedict</a></li>\n<li><a href=\"https://wha13.github.io/2024/06/13/mfcve\">https://wha13.github.io/2024/06/13/mfcve</a></li>\n<li><a href=\"https://github.com/piskvorky/sqlitedict/issues/174\">https://github.com/piskvorky/sqlitedict/issues/174</a></li>\n<li><a href=\"https://github.com/piskvorky/sqlitedict?tab=readme-ov-file#serialization\">https://github.com/piskvorky/sqlitedict?tab=readme-ov-file#serialization</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-g4r7-86gm-pgqc\">https://github.com/advisories/GHSA-g4r7-86gm-pgqc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-g4r7-86gm-pgqc",
            "title": "[sqlitedict] sqlitedict insecure deserialization vulnerability",
            "date_modified": "2024-09-18T17:39:12.000Z",
            "date_published": "2024-09-18T15:30:52.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-g4r7-86gm-pgqc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>utils.http.is_safe_url function</code> in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by <code>http://mysite.example.com\\@attacker.com</code>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-2512\">https://nvd.nist.gov/vuln/detail/CVE-2016-2512</a></li>\n<li><a href=\"https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0\">https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0502.html\">http://rhn.redhat.com/errata/RHSA-2016-0502.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0504.html\">http://rhn.redhat.com/errata/RHSA-2016-0504.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0505.html\">http://rhn.redhat.com/errata/RHSA-2016-0505.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0506.html\">http://rhn.redhat.com/errata/RHSA-2016-0506.html</a></li>\n<li><a href=\"http://www.debian.org/security/2016/dsa-3544\">http://www.debian.org/security/2016/dsa-3544</a></li>\n<li><a href=\"http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html\">http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2915-1\">http://www.ubuntu.com/usn/USN-2915-1</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2915-2\">http://www.ubuntu.com/usn/USN-2915-2</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2915-3\">http://www.ubuntu.com/usn/USN-2915-3</a></li>\n<li><a href=\"https://web.archive.org/web/20210123090815/http://www.securityfocus.com/bid/83879\">https://web.archive.org/web/20210123090815/http://www.securityfocus.com/bid/83879</a></li>\n<li><a href=\"https://web.archive.org/web/20210413200202/http://www.securitytracker.com/id/1035152\">https://web.archive.org/web/20210413200202/http://www.securitytracker.com/id/1035152</a></li>\n<li><a href=\"https://github.com/django/django/commit/382ab137312961ad62feb8109d70a5a581fe8350\">https://github.com/django/django/commit/382ab137312961ad62feb8109d70a5a581fe8350</a></li>\n<li><a href=\"https://github.com/django/django/commit/fc6d147a63f89795dbcdecb0559256470fff4380\">https://github.com/django/django/commit/fc6d147a63f89795dbcdecb0559256470fff4380</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2016/mar/01/security-releases\">https://www.djangoproject.com/weblog/2016/mar/01/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2016-15.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2016-15.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pw27-w7w4-9qc7\">https://github.com/advisories/GHSA-pw27-w7w4-9qc7</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pw27-w7w4-9qc7",
            "title": "[Django] Django XSS Vulnerability",
            "date_modified": "2024-09-18T16:21:08.000Z",
            "date_published": "2022-05-17T01:09:58.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pw27-w7w4-9qc7"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and 1.8.x before 1.8.3 uses an incorrect regular expression, which allows remote attackers to inject arbitrary headers and conduct HTTP response splitting attacks via a newline character in an (1) email message to the EmailValidator, a (2) URL to the URLValidator, or unspecified vectors to the (3) validate_ipv4_address or (4) validate_slug validator.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-5144\">https://nvd.nist.gov/vuln/detail/CVE-2015-5144</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/201510-06\">https://security.gentoo.org/glsa/201510-06</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-10/msg00043.html\">http://lists.opensuse.org/opensuse-updates/2015-10/msg00043.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-10/msg00046.html\">http://lists.opensuse.org/opensuse-updates/2015-10/msg00046.html</a></li>\n<li><a href=\"http://www.debian.org/security/2015/dsa-3305\">http://www.debian.org/security/2015/dsa-3305</a></li>\n<li><a href=\"http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html\">http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2671-1\">http://www.ubuntu.com/usn/USN-2671-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/1ba1cdce7d58e6740fe51955d945b56ae51d072a\">https://github.com/django/django/commit/1ba1cdce7d58e6740fe51955d945b56ae51d072a</a></li>\n<li><a href=\"https://github.com/django/django/commit/574dd5e0b0fbb877ae5827b1603d298edc9bb2a0\">https://github.com/django/django/commit/574dd5e0b0fbb877ae5827b1603d298edc9bb2a0</a></li>\n<li><a href=\"https://github.com/django/django/commit/ae49b4d994656bc037513dcd064cb9ce5bb85649\">https://github.com/django/django/commit/ae49b4d994656bc037513dcd064cb9ce5bb85649</a></li>\n<li><a href=\"https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.4.21.txt#L30-L54\">https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.4.21.txt#L30-L54</a></li>\n<li><a href=\"https://web.archive.org/web/20150924150801/http://www.securitytracker.com/id/1032820\">https://web.archive.org/web/20150924150801/http://www.securitytracker.com/id/1032820</a></li>\n<li><a href=\"https://web.archive.org/web/20200228050526/http://www.securityfocus.com/bid/75665\">https://web.archive.org/web/20200228050526/http://www.securityfocus.com/bid/75665</a></li>\n<li><a href=\"https://github.com/django/django/commit/8f9a4d3a2bc42f14bb437defd30c7315adbff22c\">https://github.com/django/django/commit/8f9a4d3a2bc42f14bb437defd30c7315adbff22c</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2015/jul/08/security-releases\">https://www.djangoproject.com/weblog/2015/jul/08/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-10.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-10.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-q5qw-4364-5hhm\">https://github.com/advisories/GHSA-q5qw-4364-5hhm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-q5qw-4364-5hhm",
            "title": "[Django] Django Vulnerable to HTTP Response Splitting Attack",
            "date_modified": "2024-09-18T16:19:05.000Z",
            "date_published": "2022-05-17T00:48:30.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-q5qw-4364-5hhm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and 1.8.x before 1.8.3 uses an incorrect regular expression, which allows remote attackers to inject arbitrary headers and conduct HTTP response splitting attacks via a newline character in an (1) email message to the EmailValidator, a (2) URL to the URLValidator, or unspecified vectors to the (3) validate_ipv4_address or (4) validate_slug validator.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-5144\">https://nvd.nist.gov/vuln/detail/CVE-2015-5144</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/201510-06\">https://security.gentoo.org/glsa/201510-06</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-10/msg00043.html\">http://lists.opensuse.org/opensuse-updates/2015-10/msg00043.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-10/msg00046.html\">http://lists.opensuse.org/opensuse-updates/2015-10/msg00046.html</a></li>\n<li><a href=\"http://www.debian.org/security/2015/dsa-3305\">http://www.debian.org/security/2015/dsa-3305</a></li>\n<li><a href=\"http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html\">http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2671-1\">http://www.ubuntu.com/usn/USN-2671-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/1ba1cdce7d58e6740fe51955d945b56ae51d072a\">https://github.com/django/django/commit/1ba1cdce7d58e6740fe51955d945b56ae51d072a</a></li>\n<li><a href=\"https://github.com/django/django/commit/574dd5e0b0fbb877ae5827b1603d298edc9bb2a0\">https://github.com/django/django/commit/574dd5e0b0fbb877ae5827b1603d298edc9bb2a0</a></li>\n<li><a href=\"https://github.com/django/django/commit/ae49b4d994656bc037513dcd064cb9ce5bb85649\">https://github.com/django/django/commit/ae49b4d994656bc037513dcd064cb9ce5bb85649</a></li>\n<li><a href=\"https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.4.21.txt#L30-L54\">https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.4.21.txt#L30-L54</a></li>\n<li><a href=\"https://web.archive.org/web/20150924150801/http://www.securitytracker.com/id/1032820\">https://web.archive.org/web/20150924150801/http://www.securitytracker.com/id/1032820</a></li>\n<li><a href=\"https://web.archive.org/web/20200228050526/http://www.securityfocus.com/bid/75665\">https://web.archive.org/web/20200228050526/http://www.securityfocus.com/bid/75665</a></li>\n<li><a href=\"https://github.com/django/django/commit/8f9a4d3a2bc42f14bb437defd30c7315adbff22c\">https://github.com/django/django/commit/8f9a4d3a2bc42f14bb437defd30c7315adbff22c</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2015/jul/08/security-releases\">https://www.djangoproject.com/weblog/2015/jul/08/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-10.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-10.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-q5qw-4364-5hhm\">https://github.com/advisories/GHSA-q5qw-4364-5hhm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-q5qw-4364-5hhm",
            "title": "[Django] Django Vulnerable to HTTP Response Splitting Attack",
            "date_modified": "2024-09-18T16:19:05.000Z",
            "date_published": "2022-05-17T00:48:30.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-q5qw-4364-5hhm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p><code>validators.URLValidator</code> in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-5145\">https://nvd.nist.gov/vuln/detail/CVE-2015-5145</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/201510-06\">https://security.gentoo.org/glsa/201510-06</a></li>\n<li><a href=\"https://github.com/django/django/commit/8f9a4d3a2bc42f14bb437defd30c7315adbff22c\">https://github.com/django/django/commit/8f9a4d3a2bc42f14bb437defd30c7315adbff22c</a></li>\n<li><a href=\"https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.8.3.txt#L63-L68\">https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.8.3.txt#L63-L68</a></li>\n<li><a href=\"https://web.archive.org/web/20150924150801/http://www.securitytracker.com/id/1032820\">https://web.archive.org/web/20150924150801/http://www.securitytracker.com/id/1032820</a></li>\n<li><a href=\"https://web.archive.org/web/20170526042302/http://www.securityfocus.com/bid/75691\">https://web.archive.org/web/20170526042302/http://www.securityfocus.com/bid/75691</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-21.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-21.yaml</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2015/jul/08/security-releases\">https://www.djangoproject.com/weblog/2015/jul/08/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-cqf7-ff9h-7967\">https://github.com/advisories/GHSA-cqf7-ff9h-7967</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-cqf7-ff9h-7967",
            "title": "[Django] Django ReDoS in validators.URLValidator",
            "date_modified": "2024-09-18T16:17:41.000Z",
            "date_published": "2022-05-17T00:48:30.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-cqf7-ff9h-7967"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-12781\">https://nvd.nist.gov/vuln/detail/CVE-2019-12781</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2019/07/01/3\">http://www.openwall.com/lists/oss-security/2019/07/01/3</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ\">https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Jul/10\">https://seclists.org/bugtraq/2019/Jul/10</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4476\">https://www.debian.org/security/2019/dsa-4476</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6c7v-2f49-8h26\">https://github.com/advisories/GHSA-6c7v-2f49-8h26</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-10.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-10.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190705-0002\">https://security.netapp.com/advisory/ntap-20190705-0002</a></li>\n<li><a href=\"https://usn.ubuntu.com/4043-1\">https://usn.ubuntu.com/4043-1</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/jul/01/security-releases\">https://www.djangoproject.com/weblog/2019/jul/01/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6c7v-2f49-8h26",
            "title": "[Django] Django Incorrect HTTP detection with reverse-proxy connecting via HTTPS",
            "date_modified": "2024-09-18T16:15:30.000Z",
            "date_published": "2019-07-03T20:37:25.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6c7v-2f49-8h26"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-12781\">https://nvd.nist.gov/vuln/detail/CVE-2019-12781</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2019/07/01/3\">http://www.openwall.com/lists/oss-security/2019/07/01/3</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ\">https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Jul/10\">https://seclists.org/bugtraq/2019/Jul/10</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4476\">https://www.debian.org/security/2019/dsa-4476</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6c7v-2f49-8h26\">https://github.com/advisories/GHSA-6c7v-2f49-8h26</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-10.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-10.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190705-0002\">https://security.netapp.com/advisory/ntap-20190705-0002</a></li>\n<li><a href=\"https://usn.ubuntu.com/4043-1\">https://usn.ubuntu.com/4043-1</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/jul/01/security-releases\">https://www.djangoproject.com/weblog/2019/jul/01/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6c7v-2f49-8h26",
            "title": "[Django] Django Incorrect HTTP detection with reverse-proxy connecting via HTTPS",
            "date_modified": "2024-09-18T16:15:30.000Z",
            "date_published": "2019-07-03T20:37:25.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6c7v-2f49-8h26"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-12781\">https://nvd.nist.gov/vuln/detail/CVE-2019-12781</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2019/07/01/3\">http://www.openwall.com/lists/oss-security/2019/07/01/3</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ\">https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Jul/10\">https://seclists.org/bugtraq/2019/Jul/10</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4476\">https://www.debian.org/security/2019/dsa-4476</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html\">http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security\">https://docs.djangoproject.com/en/dev/releases/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6c7v-2f49-8h26\">https://github.com/advisories/GHSA-6c7v-2f49-8h26</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-10.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2019-10.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190705-0002\">https://security.netapp.com/advisory/ntap-20190705-0002</a></li>\n<li><a href=\"https://usn.ubuntu.com/4043-1\">https://usn.ubuntu.com/4043-1</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/jul/01/security-releases\">https://www.djangoproject.com/weblog/2019/jul/01/security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6c7v-2f49-8h26",
            "title": "[Django] Django Incorrect HTTP detection with reverse-proxy connecting via HTTPS",
            "date_modified": "2024-09-18T16:15:30.000Z",
            "date_published": "2019-07-03T20:37:25.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6c7v-2f49-8h26"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django before 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3, when settings.DEBUG is True, allow remote attackers to conduct DNS rebinding attacks by leveraging failure to validate the HTTP Host header against settings.ALLOWED_HOSTS.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-9014\">https://nvd.nist.gov/vuln/detail/CVE-2016-9014</a></li>\n<li><a href=\"http://www.debian.org/security/2017/dsa-3835\">http://www.debian.org/security/2017/dsa-3835</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-3115-1\">http://www.ubuntu.com/usn/USN-3115-1</a></li>\n<li><a href=\"https://web.archive.org/web/20210123185619/http://www.securityfocus.com/bid/94068\">https://web.archive.org/web/20210123185619/http://www.securityfocus.com/bid/94068</a></li>\n<li><a href=\"https://web.archive.org/web/20211204043252/http://www.securitytracker.com/id/1037159\">https://web.archive.org/web/20211204043252/http://www.securitytracker.com/id/1037159</a></li>\n<li><a href=\"https://github.com/django/django/commit/45acd6d836895a4c36575f48b3fb36a3dae98d19\">https://github.com/django/django/commit/45acd6d836895a4c36575f48b3fb36a3dae98d19</a></li>\n<li><a href=\"https://github.com/django/django/commit/884e113838e5a72b4b0ec9e5e87aa480f6aa4472\">https://github.com/django/django/commit/884e113838e5a72b4b0ec9e5e87aa480f6aa4472</a></li>\n<li><a href=\"https://github.com/django/django/commit/c401ae9a7dfb1a94a8a61927ed541d6f93089587\">https://github.com/django/django/commit/c401ae9a7dfb1a94a8a61927ed541d6f93089587</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OG5ROMUPS6C7BXELD3TAUUH7OBYV56WQ\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OG5ROMUPS6C7BXELD3TAUUH7OBYV56WQ</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QXDKJYHN74BWY3P7AR2UZDVJREQMRE6S\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QXDKJYHN74BWY3P7AR2UZDVJREQMRE6S</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2016/nov/01/security-releases\">https://www.djangoproject.com/weblog/2016/nov/01/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2016-18.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2016-18.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3f2c-jm6v-cr35\">https://github.com/advisories/GHSA-3f2c-jm6v-cr35</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3f2c-jm6v-cr35",
            "title": "[Django] Django DNS Rebinding Vulnerability",
            "date_modified": "2024-09-18T16:11:36.000Z",
            "date_published": "2022-05-17T00:27:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3f2c-jm6v-cr35"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django before 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3, when settings.DEBUG is True, allow remote attackers to conduct DNS rebinding attacks by leveraging failure to validate the HTTP Host header against settings.ALLOWED_HOSTS.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-9014\">https://nvd.nist.gov/vuln/detail/CVE-2016-9014</a></li>\n<li><a href=\"http://www.debian.org/security/2017/dsa-3835\">http://www.debian.org/security/2017/dsa-3835</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-3115-1\">http://www.ubuntu.com/usn/USN-3115-1</a></li>\n<li><a href=\"https://web.archive.org/web/20210123185619/http://www.securityfocus.com/bid/94068\">https://web.archive.org/web/20210123185619/http://www.securityfocus.com/bid/94068</a></li>\n<li><a href=\"https://web.archive.org/web/20211204043252/http://www.securitytracker.com/id/1037159\">https://web.archive.org/web/20211204043252/http://www.securitytracker.com/id/1037159</a></li>\n<li><a href=\"https://github.com/django/django/commit/45acd6d836895a4c36575f48b3fb36a3dae98d19\">https://github.com/django/django/commit/45acd6d836895a4c36575f48b3fb36a3dae98d19</a></li>\n<li><a href=\"https://github.com/django/django/commit/884e113838e5a72b4b0ec9e5e87aa480f6aa4472\">https://github.com/django/django/commit/884e113838e5a72b4b0ec9e5e87aa480f6aa4472</a></li>\n<li><a href=\"https://github.com/django/django/commit/c401ae9a7dfb1a94a8a61927ed541d6f93089587\">https://github.com/django/django/commit/c401ae9a7dfb1a94a8a61927ed541d6f93089587</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OG5ROMUPS6C7BXELD3TAUUH7OBYV56WQ\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OG5ROMUPS6C7BXELD3TAUUH7OBYV56WQ</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QXDKJYHN74BWY3P7AR2UZDVJREQMRE6S\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QXDKJYHN74BWY3P7AR2UZDVJREQMRE6S</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2016/nov/01/security-releases\">https://www.djangoproject.com/weblog/2016/nov/01/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2016-18.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2016-18.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3f2c-jm6v-cr35\">https://github.com/advisories/GHSA-3f2c-jm6v-cr35</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3f2c-jm6v-cr35",
            "title": "[Django] Django DNS Rebinding Vulnerability",
            "date_modified": "2024-09-18T16:11:36.000Z",
            "date_published": "2022-05-17T00:27:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3f2c-jm6v-cr35"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django before 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3, when settings.DEBUG is True, allow remote attackers to conduct DNS rebinding attacks by leveraging failure to validate the HTTP Host header against settings.ALLOWED_HOSTS.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-9014\">https://nvd.nist.gov/vuln/detail/CVE-2016-9014</a></li>\n<li><a href=\"http://www.debian.org/security/2017/dsa-3835\">http://www.debian.org/security/2017/dsa-3835</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-3115-1\">http://www.ubuntu.com/usn/USN-3115-1</a></li>\n<li><a href=\"https://web.archive.org/web/20210123185619/http://www.securityfocus.com/bid/94068\">https://web.archive.org/web/20210123185619/http://www.securityfocus.com/bid/94068</a></li>\n<li><a href=\"https://web.archive.org/web/20211204043252/http://www.securitytracker.com/id/1037159\">https://web.archive.org/web/20211204043252/http://www.securitytracker.com/id/1037159</a></li>\n<li><a href=\"https://github.com/django/django/commit/45acd6d836895a4c36575f48b3fb36a3dae98d19\">https://github.com/django/django/commit/45acd6d836895a4c36575f48b3fb36a3dae98d19</a></li>\n<li><a href=\"https://github.com/django/django/commit/884e113838e5a72b4b0ec9e5e87aa480f6aa4472\">https://github.com/django/django/commit/884e113838e5a72b4b0ec9e5e87aa480f6aa4472</a></li>\n<li><a href=\"https://github.com/django/django/commit/c401ae9a7dfb1a94a8a61927ed541d6f93089587\">https://github.com/django/django/commit/c401ae9a7dfb1a94a8a61927ed541d6f93089587</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OG5ROMUPS6C7BXELD3TAUUH7OBYV56WQ\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OG5ROMUPS6C7BXELD3TAUUH7OBYV56WQ</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QXDKJYHN74BWY3P7AR2UZDVJREQMRE6S\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QXDKJYHN74BWY3P7AR2UZDVJREQMRE6S</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2016/nov/01/security-releases\">https://www.djangoproject.com/weblog/2016/nov/01/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2016-18.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2016-18.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3f2c-jm6v-cr35\">https://github.com/advisories/GHSA-3f2c-jm6v-cr35</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3f2c-jm6v-cr35",
            "title": "[Django] Django DNS Rebinding Vulnerability",
            "date_modified": "2024-09-18T16:11:36.000Z",
            "date_published": "2022-05-17T00:27:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3f2c-jm6v-cr35"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The is_safe_url function in utils/http.py in Django 1.4.x before 1.4.6, 1.5.x before 1.5.2, and 1.6 before beta 2 treats a URL's scheme as safe even if it is not HTTP or HTTPS, which might introduce cross-site scripting (XSS) or other vulnerabilities into Django applications that use this function, as demonstrated by \"the login view in django.contrib.auth.views\" and the javascript: scheme.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2013-6044\">https://nvd.nist.gov/vuln/detail/CVE-2013-6044</a></li>\n<li><a href=\"https://github.com/django/django/commit/1a274ccd6bc1afbdac80344c9b6e5810c1162b5f\">https://github.com/django/django/commit/1a274ccd6bc1afbdac80344c9b6e5810c1162b5f</a></li>\n<li><a href=\"https://github.com/django/django/commit/ae3535169af804352517b7fea94a42a1c9c4b762\">https://github.com/django/django/commit/ae3535169af804352517b7fea94a42a1c9c4b762</a></li>\n<li><a href=\"https://github.com/django/django/commit/ec67af0bd609c412b76eaa4cc89968a2a8e5ad6a\">https://github.com/django/django/commit/ec67af0bd609c412b76eaa4cc89968a2a8e5ad6a</a></li>\n<li><a href=\"https://exchange.xforce.ibmcloud.com/vulnerabilities/86437\">https://exchange.xforce.ibmcloud.com/vulnerabilities/86437</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2013/aug/13/security-releases-issued\">https://www.djangoproject.com/weblog/2013/aug/13/security-releases-issued</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2013-10/msg00015.html\">http://lists.opensuse.org/opensuse-updates/2013-10/msg00015.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2013-1521.html\">http://rhn.redhat.com/errata/RHSA-2013-1521.html</a></li>\n<li><a href=\"http://seclists.org/oss-sec/2013/q3/369\">http://seclists.org/oss-sec/2013/q3/369</a></li>\n<li><a href=\"http://seclists.org/oss-sec/2013/q3/411\">http://seclists.org/oss-sec/2013/q3/411</a></li>\n<li><a href=\"http://www.debian.org/security/2013/dsa-2740\">http://www.debian.org/security/2013/dsa-2740</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2013-21.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2013-21.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-9cwg-mhxf-hh59\">https://github.com/advisories/GHSA-9cwg-mhxf-hh59</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-9cwg-mhxf-hh59",
            "title": "[Django] Django cross-site scripting (XSS) vulnerability via is_safe_url function ",
            "date_modified": "2024-09-18T16:09:44.000Z",
            "date_published": "2022-05-17T00:23:23.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-9cwg-mhxf-hh59"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The is_safe_url function in utils/http.py in Django 1.4.x before 1.4.6, 1.5.x before 1.5.2, and 1.6 before beta 2 treats a URL's scheme as safe even if it is not HTTP or HTTPS, which might introduce cross-site scripting (XSS) or other vulnerabilities into Django applications that use this function, as demonstrated by \"the login view in django.contrib.auth.views\" and the javascript: scheme.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2013-6044\">https://nvd.nist.gov/vuln/detail/CVE-2013-6044</a></li>\n<li><a href=\"https://github.com/django/django/commit/1a274ccd6bc1afbdac80344c9b6e5810c1162b5f\">https://github.com/django/django/commit/1a274ccd6bc1afbdac80344c9b6e5810c1162b5f</a></li>\n<li><a href=\"https://github.com/django/django/commit/ae3535169af804352517b7fea94a42a1c9c4b762\">https://github.com/django/django/commit/ae3535169af804352517b7fea94a42a1c9c4b762</a></li>\n<li><a href=\"https://github.com/django/django/commit/ec67af0bd609c412b76eaa4cc89968a2a8e5ad6a\">https://github.com/django/django/commit/ec67af0bd609c412b76eaa4cc89968a2a8e5ad6a</a></li>\n<li><a href=\"https://exchange.xforce.ibmcloud.com/vulnerabilities/86437\">https://exchange.xforce.ibmcloud.com/vulnerabilities/86437</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2013/aug/13/security-releases-issued\">https://www.djangoproject.com/weblog/2013/aug/13/security-releases-issued</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2013-10/msg00015.html\">http://lists.opensuse.org/opensuse-updates/2013-10/msg00015.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2013-1521.html\">http://rhn.redhat.com/errata/RHSA-2013-1521.html</a></li>\n<li><a href=\"http://seclists.org/oss-sec/2013/q3/369\">http://seclists.org/oss-sec/2013/q3/369</a></li>\n<li><a href=\"http://seclists.org/oss-sec/2013/q3/411\">http://seclists.org/oss-sec/2013/q3/411</a></li>\n<li><a href=\"http://www.debian.org/security/2013/dsa-2740\">http://www.debian.org/security/2013/dsa-2740</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2013-21.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2013-21.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-9cwg-mhxf-hh59\">https://github.com/advisories/GHSA-9cwg-mhxf-hh59</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-9cwg-mhxf-hh59",
            "title": "[Django] Django cross-site scripting (XSS) vulnerability via is_safe_url function ",
            "date_modified": "2024-09-18T16:09:44.000Z",
            "date_published": "2022-05-17T00:23:23.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-9cwg-mhxf-hh59"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18 relies on user input in some cases to redirect the user to an \"on success\" URL. The security check for these redirects (namely <code>django.utils.http.is_safe_url()</code>) considered some numeric URLs \"safe\" when they shouldn't be, aka an open redirect vulnerability. Also, if a developer relies on <code>is_safe_url()</code> to provide safe redirect targets and puts such a URL into a link, they could suffer from an XSS attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-7233\">https://nvd.nist.gov/vuln/detail/CVE-2017-7233</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1445\">https://access.redhat.com/errata/RHSA-2017:1445</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1451\">https://access.redhat.com/errata/RHSA-2017:1451</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1462\">https://access.redhat.com/errata/RHSA-2017:1462</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1470\">https://access.redhat.com/errata/RHSA-2017:1470</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1596\">https://access.redhat.com/errata/RHSA-2017:1596</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:3093\">https://access.redhat.com/errata/RHSA-2017:3093</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2927\">https://access.redhat.com/errata/RHSA-2018:2927</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-37hp-765x-j95x\">https://github.com/advisories/GHSA-37hp-765x-j95x</a></li>\n<li><a href=\"http://www.debian.org/security/2017/dsa-3835\">http://www.debian.org/security/2017/dsa-3835</a></li>\n<li><a href=\"https://github.com/django/django/commit/254326cb3682389f55f886804d2c43f7b9f23e4f\">https://github.com/django/django/commit/254326cb3682389f55f886804d2c43f7b9f23e4f</a></li>\n<li><a href=\"https://github.com/django/django/commit/8339277518c7d8ec280070a780915304654e3b66\">https://github.com/django/django/commit/8339277518c7d8ec280070a780915304654e3b66</a></li>\n<li><a href=\"https://github.com/django/django/commit/f824655bc2c50b19d2f202d7640785caabc82787\">https://github.com/django/django/commit/f824655bc2c50b19d2f202d7640785caabc82787</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2017/apr/04/security-releases\">https://www.djangoproject.com/weblog/2017/apr/04/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2017-9.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2017-9.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-37hp-765x-j95x",
            "title": "[Django] Django open redirect and possible XSS attack via user-supplied numeric redirect URLs",
            "date_modified": "2024-09-18T16:08:54.000Z",
            "date_published": "2019-01-04T17:50:26.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-37hp-765x-j95x"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18 relies on user input in some cases to redirect the user to an \"on success\" URL. The security check for these redirects (namely <code>django.utils.http.is_safe_url()</code>) considered some numeric URLs \"safe\" when they shouldn't be, aka an open redirect vulnerability. Also, if a developer relies on <code>is_safe_url()</code> to provide safe redirect targets and puts such a URL into a link, they could suffer from an XSS attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-7233\">https://nvd.nist.gov/vuln/detail/CVE-2017-7233</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1445\">https://access.redhat.com/errata/RHSA-2017:1445</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1451\">https://access.redhat.com/errata/RHSA-2017:1451</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1462\">https://access.redhat.com/errata/RHSA-2017:1462</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1470\">https://access.redhat.com/errata/RHSA-2017:1470</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1596\">https://access.redhat.com/errata/RHSA-2017:1596</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:3093\">https://access.redhat.com/errata/RHSA-2017:3093</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2927\">https://access.redhat.com/errata/RHSA-2018:2927</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-37hp-765x-j95x\">https://github.com/advisories/GHSA-37hp-765x-j95x</a></li>\n<li><a href=\"http://www.debian.org/security/2017/dsa-3835\">http://www.debian.org/security/2017/dsa-3835</a></li>\n<li><a href=\"https://github.com/django/django/commit/254326cb3682389f55f886804d2c43f7b9f23e4f\">https://github.com/django/django/commit/254326cb3682389f55f886804d2c43f7b9f23e4f</a></li>\n<li><a href=\"https://github.com/django/django/commit/8339277518c7d8ec280070a780915304654e3b66\">https://github.com/django/django/commit/8339277518c7d8ec280070a780915304654e3b66</a></li>\n<li><a href=\"https://github.com/django/django/commit/f824655bc2c50b19d2f202d7640785caabc82787\">https://github.com/django/django/commit/f824655bc2c50b19d2f202d7640785caabc82787</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2017/apr/04/security-releases\">https://www.djangoproject.com/weblog/2017/apr/04/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2017-9.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2017-9.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-37hp-765x-j95x",
            "title": "[Django] Django open redirect and possible XSS attack via user-supplied numeric redirect URLs",
            "date_modified": "2024-09-18T16:08:54.000Z",
            "date_published": "2019-01-04T17:50:26.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-37hp-765x-j95x"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18 relies on user input in some cases to redirect the user to an \"on success\" URL. The security check for these redirects (namely <code>django.utils.http.is_safe_url()</code>) considered some numeric URLs \"safe\" when they shouldn't be, aka an open redirect vulnerability. Also, if a developer relies on <code>is_safe_url()</code> to provide safe redirect targets and puts such a URL into a link, they could suffer from an XSS attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-7233\">https://nvd.nist.gov/vuln/detail/CVE-2017-7233</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1445\">https://access.redhat.com/errata/RHSA-2017:1445</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1451\">https://access.redhat.com/errata/RHSA-2017:1451</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1462\">https://access.redhat.com/errata/RHSA-2017:1462</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1470\">https://access.redhat.com/errata/RHSA-2017:1470</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1596\">https://access.redhat.com/errata/RHSA-2017:1596</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:3093\">https://access.redhat.com/errata/RHSA-2017:3093</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2927\">https://access.redhat.com/errata/RHSA-2018:2927</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-37hp-765x-j95x\">https://github.com/advisories/GHSA-37hp-765x-j95x</a></li>\n<li><a href=\"http://www.debian.org/security/2017/dsa-3835\">http://www.debian.org/security/2017/dsa-3835</a></li>\n<li><a href=\"https://github.com/django/django/commit/254326cb3682389f55f886804d2c43f7b9f23e4f\">https://github.com/django/django/commit/254326cb3682389f55f886804d2c43f7b9f23e4f</a></li>\n<li><a href=\"https://github.com/django/django/commit/8339277518c7d8ec280070a780915304654e3b66\">https://github.com/django/django/commit/8339277518c7d8ec280070a780915304654e3b66</a></li>\n<li><a href=\"https://github.com/django/django/commit/f824655bc2c50b19d2f202d7640785caabc82787\">https://github.com/django/django/commit/f824655bc2c50b19d2f202d7640785caabc82787</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2017/apr/04/security-releases\">https://www.djangoproject.com/weblog/2017/apr/04/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2017-9.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2017-9.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-37hp-765x-j95x",
            "title": "[Django] Django open redirect and possible XSS attack via user-supplied numeric redirect URLs",
            "date_modified": "2024-09-18T16:08:54.000Z",
            "date_published": "2019-01-04T17:50:26.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-37hp-765x-j95x"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>contrib.auth.middleware.RemoteUserMiddleware</code> middleware in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3, when using the <code>contrib.auth.backends.RemoteUserBackend</code> backend, allows remote authenticated users to hijack web sessions via vectors related to the <code>REMOTE_USER</code> header.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2014-0482\">https://nvd.nist.gov/vuln/detail/CVE-2014-0482</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html\">http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html</a></li>\n<li><a href=\"http://www.debian.org/security/2014/dsa-3010\">http://www.debian.org/security/2014/dsa-3010</a></li>\n<li><a href=\"https://github.com/django/django/commit/0268b855f9eab3377f2821164ef3e66037789e09\">https://github.com/django/django/commit/0268b855f9eab3377f2821164ef3e66037789e09</a></li>\n<li><a href=\"https://github.com/django/django/commit/5307ce565fbedb9cc27cbe7c757b41a00438d37c\">https://github.com/django/django/commit/5307ce565fbedb9cc27cbe7c757b41a00438d37c</a></li>\n<li><a href=\"https://github.com/django/django/commit/c9e3b9949cd55f090591fbdc4a114fcb8368b6d9\">https://github.com/django/django/commit/c9e3b9949cd55f090591fbdc4a114fcb8368b6d9</a></li>\n<li><a href=\"https://github.com/django/django/commit/dd68f319b365f6cb38c5a6c106faf4f6142d7d88\">https://github.com/django/django/commit/dd68f319b365f6cb38c5a6c106faf4f6142d7d88</a></li>\n<li><a href=\"https://github.com/django/django/blob/aa3cb3f37265be37d892e2b391ff023e9caee2a4/docs/releases/1.5.9.txt#L42\">https://github.com/django/django/blob/aa3cb3f37265be37d892e2b391ff023e9caee2a4/docs/releases/1.5.9.txt#L42</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2014-6.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2014-6.yaml</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2014/aug/20/security\">https://www.djangoproject.com/weblog/2014/aug/20/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-625g-gx8c-xcmg\">https://github.com/advisories/GHSA-625g-gx8c-xcmg</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-625g-gx8c-xcmg",
            "title": "[Django] Django Middleware Enables Session Hijacking",
            "date_modified": "2024-09-18T16:06:44.000Z",
            "date_published": "2022-05-14T02:09:22.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-625g-gx8c-xcmg"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>contrib.auth.middleware.RemoteUserMiddleware</code> middleware in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3, when using the <code>contrib.auth.backends.RemoteUserBackend</code> backend, allows remote authenticated users to hijack web sessions via vectors related to the <code>REMOTE_USER</code> header.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2014-0482\">https://nvd.nist.gov/vuln/detail/CVE-2014-0482</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html\">http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html</a></li>\n<li><a href=\"http://www.debian.org/security/2014/dsa-3010\">http://www.debian.org/security/2014/dsa-3010</a></li>\n<li><a href=\"https://github.com/django/django/commit/0268b855f9eab3377f2821164ef3e66037789e09\">https://github.com/django/django/commit/0268b855f9eab3377f2821164ef3e66037789e09</a></li>\n<li><a href=\"https://github.com/django/django/commit/5307ce565fbedb9cc27cbe7c757b41a00438d37c\">https://github.com/django/django/commit/5307ce565fbedb9cc27cbe7c757b41a00438d37c</a></li>\n<li><a href=\"https://github.com/django/django/commit/c9e3b9949cd55f090591fbdc4a114fcb8368b6d9\">https://github.com/django/django/commit/c9e3b9949cd55f090591fbdc4a114fcb8368b6d9</a></li>\n<li><a href=\"https://github.com/django/django/commit/dd68f319b365f6cb38c5a6c106faf4f6142d7d88\">https://github.com/django/django/commit/dd68f319b365f6cb38c5a6c106faf4f6142d7d88</a></li>\n<li><a href=\"https://github.com/django/django/blob/aa3cb3f37265be37d892e2b391ff023e9caee2a4/docs/releases/1.5.9.txt#L42\">https://github.com/django/django/blob/aa3cb3f37265be37d892e2b391ff023e9caee2a4/docs/releases/1.5.9.txt#L42</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2014-6.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2014-6.yaml</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2014/aug/20/security\">https://www.djangoproject.com/weblog/2014/aug/20/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-625g-gx8c-xcmg\">https://github.com/advisories/GHSA-625g-gx8c-xcmg</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-625g-gx8c-xcmg",
            "title": "[Django] Django Middleware Enables Session Hijacking",
            "date_modified": "2024-09-18T16:06:44.000Z",
            "date_published": "2022-05-14T02:09:22.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-625g-gx8c-xcmg"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}