{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>A command injection vulnerability exists in the RunGptLLM class of the llama_index library, version 0.9.47, used by the RunGpt framework from JinaAI to connect to Language Learning Models (LLMs). The vulnerability arises from the improper use of the eval function, allowing a malicious or compromised LLM hosting provider to execute arbitrary commands on the client's machine. This issue was fixed in version 0.10.13. The exploitation of this vulnerability could lead to a hosting provider gaining full control over client machines.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-4181\">https://nvd.nist.gov/vuln/detail/CVE-2024-4181</a></li>\n<li><a href=\"https://github.com/run-llama/llama_index/commit/d73715eaf0642705583e7897c78b9c8dd2d3a7ba\">https://github.com/run-llama/llama_index/commit/d73715eaf0642705583e7897c78b9c8dd2d3a7ba</a></li>\n<li><a href=\"https://huntr.com/bounties/1a204520-598a-434e-b13d-0d34f2a5ddc1\">https://huntr.com/bounties/1a204520-598a-434e-b13d-0d34f2a5ddc1</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pw38-xv9x-h8ch\">https://github.com/advisories/GHSA-pw38-xv9x-h8ch</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pw38-xv9x-h8ch",
            "title": "[llama-index-llms-rungpt] RunGptLLM class in LlamaIndex has a command injection",
            "date_modified": "2024-05-24T19:21:22.000Z",
            "date_published": "2024-05-16T09:33:08.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pw38-xv9x-h8ch"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A command injection vulnerability exists in the RunGptLLM class of the llama_index library, version 0.9.47, used by the RunGpt framework from JinaAI to connect to Language Learning Models (LLMs). The vulnerability arises from the improper use of the eval function, allowing a malicious or compromised LLM hosting provider to execute arbitrary commands on the client's machine. This issue was fixed in version 0.10.13. The exploitation of this vulnerability could lead to a hosting provider gaining full control over client machines.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-4181\">https://nvd.nist.gov/vuln/detail/CVE-2024-4181</a></li>\n<li><a href=\"https://github.com/run-llama/llama_index/commit/d73715eaf0642705583e7897c78b9c8dd2d3a7ba\">https://github.com/run-llama/llama_index/commit/d73715eaf0642705583e7897c78b9c8dd2d3a7ba</a></li>\n<li><a href=\"https://huntr.com/bounties/1a204520-598a-434e-b13d-0d34f2a5ddc1\">https://huntr.com/bounties/1a204520-598a-434e-b13d-0d34f2a5ddc1</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pw38-xv9x-h8ch\">https://github.com/advisories/GHSA-pw38-xv9x-h8ch</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pw38-xv9x-h8ch",
            "title": "[llama-index] RunGptLLM class in LlamaIndex has a command injection",
            "date_modified": "2024-05-24T19:21:22.000Z",
            "date_published": "2024-05-16T09:33:08.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pw38-xv9x-h8ch"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The XML libraries for Python as used in OpenStack Keystone Essex and Folsom, Django, and possibly other products allow remote attackers to read arbitrary files via an XML external entity declaration in conjunction with an entity reference, aka an XML External Entity (XXE) attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2013-1665\">https://nvd.nist.gov/vuln/detail/CVE-2013-1665</a></li>\n<li><a href=\"https://bugs.launchpad.net/keystone/+bug/1100279\">https://bugs.launchpad.net/keystone/+bug/1100279</a></li>\n<li><a href=\"http://blog.python.org/2013/02/announcing-defusedxml-fixes-for-xml.html\">http://blog.python.org/2013/02/announcing-defusedxml-fixes-for-xml.html</a></li>\n<li><a href=\"http://bugs.python.org/issue17239\">http://bugs.python.org/issue17239</a></li>\n<li><a href=\"http://lists.openstack.org/pipermail/openstack-announce/2013-February/000078.html\">http://lists.openstack.org/pipermail/openstack-announce/2013-February/000078.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2013-0657.html\">http://rhn.redhat.com/errata/RHSA-2013-0657.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2013-0658.html\">http://rhn.redhat.com/errata/RHSA-2013-0658.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2013-0670.html\">http://rhn.redhat.com/errata/RHSA-2013-0670.html</a></li>\n<li><a href=\"http://ubuntu.com/usn/usn-1757-1\">http://ubuntu.com/usn/usn-1757-1</a></li>\n<li><a href=\"http://www.debian.org/security/2013/dsa-2634\">http://www.debian.org/security/2013/dsa-2634</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2013/02/19/2\">http://www.openwall.com/lists/oss-security/2013/02/19/2</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2013/02/19/4\">http://www.openwall.com/lists/oss-security/2013/02/19/4</a></li>\n<li><a href=\"https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40\">https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40</a></li>\n<li><a href=\"https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112\">https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-x64m-686f-fmm3\">https://github.com/advisories/GHSA-x64m-686f-fmm3</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-x64m-686f-fmm3",
            "title": "[Django] XML External Entity (XXE) in Django",
            "date_modified": "2024-05-24T19:21:22.000Z",
            "date_published": "2022-05-17T05:09:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-x64m-686f-fmm3"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The XML libraries for Python as used in OpenStack Keystone Essex and Folsom, Django, and possibly other products allow remote attackers to read arbitrary files via an XML external entity declaration in conjunction with an entity reference, aka an XML External Entity (XXE) attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2013-1665\">https://nvd.nist.gov/vuln/detail/CVE-2013-1665</a></li>\n<li><a href=\"https://bugs.launchpad.net/keystone/+bug/1100279\">https://bugs.launchpad.net/keystone/+bug/1100279</a></li>\n<li><a href=\"http://blog.python.org/2013/02/announcing-defusedxml-fixes-for-xml.html\">http://blog.python.org/2013/02/announcing-defusedxml-fixes-for-xml.html</a></li>\n<li><a href=\"http://bugs.python.org/issue17239\">http://bugs.python.org/issue17239</a></li>\n<li><a href=\"http://lists.openstack.org/pipermail/openstack-announce/2013-February/000078.html\">http://lists.openstack.org/pipermail/openstack-announce/2013-February/000078.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2013-0657.html\">http://rhn.redhat.com/errata/RHSA-2013-0657.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2013-0658.html\">http://rhn.redhat.com/errata/RHSA-2013-0658.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2013-0670.html\">http://rhn.redhat.com/errata/RHSA-2013-0670.html</a></li>\n<li><a href=\"http://ubuntu.com/usn/usn-1757-1\">http://ubuntu.com/usn/usn-1757-1</a></li>\n<li><a href=\"http://www.debian.org/security/2013/dsa-2634\">http://www.debian.org/security/2013/dsa-2634</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2013/02/19/2\">http://www.openwall.com/lists/oss-security/2013/02/19/2</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2013/02/19/4\">http://www.openwall.com/lists/oss-security/2013/02/19/4</a></li>\n<li><a href=\"https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40\">https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40</a></li>\n<li><a href=\"https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112\">https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-x64m-686f-fmm3\">https://github.com/advisories/GHSA-x64m-686f-fmm3</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-x64m-686f-fmm3",
            "title": "[Django] XML External Entity (XXE) in Django",
            "date_modified": "2024-05-24T19:21:22.000Z",
            "date_published": "2022-05-17T05:09:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-x64m-686f-fmm3"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access to an arbitrary URL with no timeout, which allows remote attackers to cause a denial of service (resource consumption) via a URL associated with (1) a slow response, (2) a completed TCP connection with no application data sent, or (3) a large amount of application data, a related issue to CVE-2011-1521.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4137\">https://nvd.nist.gov/vuln/detail/CVE-2011-4137</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3jqw-crqj-w8qw\">https://github.com/advisories/GHSA-3jqw-crqj-w8qw</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/15/5\">http://openwall.com/lists/oss-security/2011/09/15/5</a></li>\n<li><a href=\"http://secunia.com/advisories/46614\">http://secunia.com/advisories/46614</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0\">https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0</a></li>\n<li><a href=\"https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930\">https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw",
            "title": "[django] Denial of service in django",
            "date_modified": "2024-05-24T19:21:22.000Z",
            "date_published": "2018-07-23T19:51:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access to an arbitrary URL with no timeout, which allows remote attackers to cause a denial of service (resource consumption) via a URL associated with (1) a slow response, (2) a completed TCP connection with no application data sent, or (3) a large amount of application data, a related issue to CVE-2011-1521.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4137\">https://nvd.nist.gov/vuln/detail/CVE-2011-4137</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3jqw-crqj-w8qw\">https://github.com/advisories/GHSA-3jqw-crqj-w8qw</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/15/5\">http://openwall.com/lists/oss-security/2011/09/15/5</a></li>\n<li><a href=\"http://secunia.com/advisories/46614\">http://secunia.com/advisories/46614</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0\">https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0</a></li>\n<li><a href=\"https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930\">https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw",
            "title": "[django] Denial of service in django",
            "date_modified": "2024-05-24T19:21:22.000Z",
            "date_published": "2018-07-23T19:51:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Aodh as packaged in Openstack Ocata and Newton before change-ID I8fd11a7f9fe3c0ea5f9843a89686ac06713b7851 and before Pike-rc1 does not verify that trust IDs belong to the user when creating alarm action with the scheme trust+http, which allows remote authenticated users with knowledge of trust IDs where Aodh is the trustee to obtain a Keystone token and perform unspecified authenticated actions by adding an alarm action with the scheme trust+http, and providing a trust id where Aodh is the trustee.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-12440\">https://nvd.nist.gov/vuln/detail/CVE-2017-12440</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:3227\">https://access.redhat.com/errata/RHSA-2017:3227</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:0315\">https://access.redhat.com/errata/RHSA-2018:0315</a></li>\n<li><a href=\"https://bugs.launchpad.net/ossn/+bug/1649333\">https://bugs.launchpad.net/ossn/+bug/1649333</a></li>\n<li><a href=\"http://www.debian.org/security/2017/dsa-3953\">http://www.debian.org/security/2017/dsa-3953</a></li>\n<li><a href=\"http://www.securityfocus.com/bid/100455\">http://www.securityfocus.com/bid/100455</a></li>\n<li><a href=\"https://github.com/openstack/aodh/commit/149d3ad2193b4d17df801f82a0a6be62dba564db\">https://github.com/openstack/aodh/commit/149d3ad2193b4d17df801f82a0a6be62dba564db</a></li>\n<li><a href=\"https://github.com/openstack/aodh/commit/92182de328d1f088c5f5a68326d2b207b21e06ea\">https://github.com/openstack/aodh/commit/92182de328d1f088c5f5a68326d2b207b21e06ea</a></li>\n<li><a href=\"https://review.openstack.org/#/c/493823\">https://review.openstack.org/#/c/493823</a></li>\n<li><a href=\"https://review.openstack.org/#/c/493824\">https://review.openstack.org/#/c/493824</a></li>\n<li><a href=\"https://review.openstack.org/#/c/493826\">https://review.openstack.org/#/c/493826</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-86cv-9gpx-6hwj\">https://github.com/advisories/GHSA-86cv-9gpx-6hwj</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-86cv-9gpx-6hwj",
            "title": "[aodh] Openstack Aodh can be used to launder Keystone trusts",
            "date_modified": "2024-05-24T05:03:43.000Z",
            "date_published": "2022-05-13T01:42:42.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-86cv-9gpx-6hwj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>OpenStack Identity (Keystone) before 2013.1 allows remote attackers to cause a denial of service (memory consumption and crash) via multiple long requests.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2013-2014\">https://nvd.nist.gov/vuln/detail/CVE-2013-2014</a></li>\n<li><a href=\"https://bugs.launchpad.net/keystone/+bug/1098177\">https://bugs.launchpad.net/keystone/+bug/1098177</a></li>\n<li><a href=\"https://bugs.launchpad.net/keystone/+bug/1099025\">https://bugs.launchpad.net/keystone/+bug/1099025</a></li>\n<li><a href=\"https://exchange.xforce.ibmcloud.com/vulnerabilities/84347\">https://exchange.xforce.ibmcloud.com/vulnerabilities/84347</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2013-July/111914.html\">http://lists.fedoraproject.org/pipermail/package-announce/2013-July/111914.html</a></li>\n<li><a href=\"http://secunia.com/advisories/53397\">http://secunia.com/advisories/53397</a></li>\n<li><a href=\"http://www.securityfocus.com/bid/59936\">http://www.securityfocus.com/bid/59936</a></li>\n<li><a href=\"https://github.com/openstack/keystone/commit/7691276b869a86c2b75631d5bede9f61e030d9d8\">https://github.com/openstack/keystone/commit/7691276b869a86c2b75631d5bede9f61e030d9d8</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-7332-36h8-8jh8\">https://github.com/advisories/GHSA-7332-36h8-8jh8</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-7332-36h8-8jh8",
            "title": "[keystone] OpenStack Identity (Keystone) Denial of Service",
            "date_modified": "2024-05-24T05:03:42.000Z",
            "date_published": "2022-05-13T01:26:09.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-7332-36h8-8jh8"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in OpenStack Nova 15.x through 15.1.0 and 16.x through 16.1.1. By detaching and reattaching an encrypted volume, an attacker may access the underlying raw volume and corrupt the LUKS header, resulting in a denial of service attack on the compute host. (The same code error also results in data loss, but that is not a vulnerability because the user loses their own data.) All Nova setups supporting encrypted volumes are affected.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-18191\">https://nvd.nist.gov/vuln/detail/CVE-2017-18191</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2332\">https://access.redhat.com/errata/RHSA-2018:2332</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2714\">https://access.redhat.com/errata/RHSA-2018:2714</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2855\">https://access.redhat.com/errata/RHSA-2018:2855</a></li>\n<li><a href=\"https://launchpad.net/bugs/1739593\">https://launchpad.net/bugs/1739593</a></li>\n<li><a href=\"https://review.openstack.org/539893\">https://review.openstack.org/539893</a></li>\n<li><a href=\"https://security.openstack.org/ossa/OSSA-2018-001.html\">https://security.openstack.org/ossa/OSSA-2018-001.html</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2018/04/20/3\">http://openwall.com/lists/oss-security/2018/04/20/3</a></li>\n<li><a href=\"http://www.securityfocus.com/bid/103104\">http://www.securityfocus.com/bid/103104</a></li>\n<li><a href=\"https://github.com/openstack/nova/commit/0225a61fc4557c1257383a654f0741f7ef2ddeac\">https://github.com/openstack/nova/commit/0225a61fc4557c1257383a654f0741f7ef2ddeac</a></li>\n<li><a href=\"https://github.com/openstack/nova/commit/5b64a1936122eeb35f37a09f9d38159e1a224c58\">https://github.com/openstack/nova/commit/5b64a1936122eeb35f37a09f9d38159e1a224c58</a></li>\n<li><a href=\"https://github.com/openstack/nova/commit/cd3eb60c2c00bcccfa9ccd4bf9d1a96ae7a5cd88\">https://github.com/openstack/nova/commit/cd3eb60c2c00bcccfa9ccd4bf9d1a96ae7a5cd88</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-ffmh-r67w-m88f\">https://github.com/advisories/GHSA-ffmh-r67w-m88f</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-ffmh-r67w-m88f",
            "title": "[nova] OpenStack Nova Denial of service attack on the compute host",
            "date_modified": "2024-05-24T05:03:39.000Z",
            "date_published": "2022-05-13T01:44:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-ffmh-r67w-m88f"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in OpenStack Nova 15.x through 15.1.0 and 16.x through 16.1.1. By detaching and reattaching an encrypted volume, an attacker may access the underlying raw volume and corrupt the LUKS header, resulting in a denial of service attack on the compute host. (The same code error also results in data loss, but that is not a vulnerability because the user loses their own data.) All Nova setups supporting encrypted volumes are affected.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-18191\">https://nvd.nist.gov/vuln/detail/CVE-2017-18191</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2332\">https://access.redhat.com/errata/RHSA-2018:2332</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2714\">https://access.redhat.com/errata/RHSA-2018:2714</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2018:2855\">https://access.redhat.com/errata/RHSA-2018:2855</a></li>\n<li><a href=\"https://launchpad.net/bugs/1739593\">https://launchpad.net/bugs/1739593</a></li>\n<li><a href=\"https://review.openstack.org/539893\">https://review.openstack.org/539893</a></li>\n<li><a href=\"https://security.openstack.org/ossa/OSSA-2018-001.html\">https://security.openstack.org/ossa/OSSA-2018-001.html</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2018/04/20/3\">http://openwall.com/lists/oss-security/2018/04/20/3</a></li>\n<li><a href=\"http://www.securityfocus.com/bid/103104\">http://www.securityfocus.com/bid/103104</a></li>\n<li><a href=\"https://github.com/openstack/nova/commit/0225a61fc4557c1257383a654f0741f7ef2ddeac\">https://github.com/openstack/nova/commit/0225a61fc4557c1257383a654f0741f7ef2ddeac</a></li>\n<li><a href=\"https://github.com/openstack/nova/commit/5b64a1936122eeb35f37a09f9d38159e1a224c58\">https://github.com/openstack/nova/commit/5b64a1936122eeb35f37a09f9d38159e1a224c58</a></li>\n<li><a href=\"https://github.com/openstack/nova/commit/cd3eb60c2c00bcccfa9ccd4bf9d1a96ae7a5cd88\">https://github.com/openstack/nova/commit/cd3eb60c2c00bcccfa9ccd4bf9d1a96ae7a5cd88</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-ffmh-r67w-m88f\">https://github.com/advisories/GHSA-ffmh-r67w-m88f</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-ffmh-r67w-m88f",
            "title": "[nova] OpenStack Nova Denial of service attack on the compute host",
            "date_modified": "2024-05-24T05:03:39.000Z",
            "date_published": "2022-05-13T01:44:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-ffmh-r67w-m88f"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Apache Airflow version 2.9.0 has a vulnerability that allows an authenticated attacker to inject malicious data into the task instance logs.&nbsp;\nUsers are recommended to upgrade to version 2.9.1, which fixes this issue.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-32077\">https://nvd.nist.gov/vuln/detail/CVE-2024-32077</a></li>\n<li><a href=\"https://github.com/apache/airflow/pull/38882\">https://github.com/apache/airflow/pull/38882</a></li>\n<li><a href=\"https://lists.apache.org/thread/gsjmnrqb3m5fzp0vgpty1jxcywo91v77\">https://lists.apache.org/thread/gsjmnrqb3m5fzp0vgpty1jxcywo91v77</a></li>\n<li><a href=\"https://github.com/apache/airflow/commit/87acf61f574daf47ce9e03a986e352a2c727f4ce\">https://github.com/apache/airflow/commit/87acf61f574daf47ce9e03a986e352a2c727f4ce</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-52gm-qmg3-r4qp\">https://github.com/advisories/GHSA-52gm-qmg3-r4qp</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-52gm-qmg3-r4qp",
            "title": "[apache-airflow] Apache Airflow: XSS vulnerability in Task Instance Log/Log Details",
            "date_modified": "2024-05-24T05:03:37.000Z",
            "date_published": "2024-05-14T18:31:00.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-52gm-qmg3-r4qp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"summary\">Summary</h3>\n<p>The Azure Storage Encryption library in Java and other languages is vulnerable to a CBC Padding Oracle attack, similar to CVE-2020-8911. The library is not vulnerable to the equivalent of CVE-2020-8912, but only because it currently only supports AES-CBC as encryption mode. </p>\n<h3 id=\"severity\">Severity</h3>\n<p>Moderate - The vulnerability poses insider risks/privilege escalation risks, circumventing controls for stored data.</p>\n<h3 id=\"further-analysis\">Further Analysis</h3>\n<p>The Java Azure Blob Storage Encryption SDK is impacted by an issue that can result in loss of confidentiality and message forgery. The attack requires write access to the container in question, and that the attacker has access to an endpoint that reveals decryption failures (without revealing the plaintext) and that when encrypting the CBC option was chosen as content cipher.</p>\n<p>This advisory describes the plaintext revealing vulnerabilities in the Java Azure Blob Storage Encryption SDK, with a similar issue in the other blob storage SDKs being present as well.</p>\n<p>In the current version of the Azure Blob Storage crypto SDK, the only algorithm option that allows users to encrypt files is to AES-CBC, without computing a MAC on the data.</p>\n<p>This exposes a padding oracle vulnerability: If the attacker has write access to the blob container bucket and can observe whether or not an endpoint with access to the key can decrypt a file (without observing the file contents that the endpoint learns in the process), they can reconstruct the plaintext with (on average) 128*length(plaintext) queries to the endpoint, by exploiting CBC's ability to manipulate the bytes of the next block and PKCS5 padding errors.</p>\n<h3 id=\"timeline\">Timeline</h3>\n<p><strong>Date reported</strong>: March 29 2022\n<strong>Date preview</strong>: June 16 2022\n<strong>Date GA</strong>: July 11 2022\n<strong>Date disclosed</strong>: July 17 2022</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-30187\">https://nvd.nist.gov/vuln/detail/CVE-2022-30187</a></li>\n<li><a href=\"https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2022-30187\">https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2022-30187</a></li>\n<li><a href=\"https://github.com/google/security-research/security/advisories/GHSA-6m8q-r22q-vfxh\">https://github.com/google/security-research/security/advisories/GHSA-6m8q-r22q-vfxh</a></li>\n<li><a href=\"https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-30187\">https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-30187</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-64x4-9hc6-r2h6\">https://github.com/advisories/GHSA-64x4-9hc6-r2h6</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-64x4-9hc6-r2h6",
            "title": "[azure-storage-blob] Microsoft: CBC Padding Oracle in Azure Blob Storage Encryption Library",
            "date_modified": "2024-05-23T17:12:44.000Z",
            "date_published": "2022-07-13T00:00:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-64x4-9hc6-r2h6"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"summary\">Summary</h3>\n<p>The Azure Storage Encryption library in Java and other languages is vulnerable to a CBC Padding Oracle attack, similar to CVE-2020-8911. The library is not vulnerable to the equivalent of CVE-2020-8912, but only because it currently only supports AES-CBC as encryption mode. </p>\n<h3 id=\"severity\">Severity</h3>\n<p>Moderate - The vulnerability poses insider risks/privilege escalation risks, circumventing controls for stored data.</p>\n<h3 id=\"further-analysis\">Further Analysis</h3>\n<p>The Java Azure Blob Storage Encryption SDK is impacted by an issue that can result in loss of confidentiality and message forgery. The attack requires write access to the container in question, and that the attacker has access to an endpoint that reveals decryption failures (without revealing the plaintext) and that when encrypting the CBC option was chosen as content cipher.</p>\n<p>This advisory describes the plaintext revealing vulnerabilities in the Java Azure Blob Storage Encryption SDK, with a similar issue in the other blob storage SDKs being present as well.</p>\n<p>In the current version of the Azure Blob Storage crypto SDK, the only algorithm option that allows users to encrypt files is to AES-CBC, without computing a MAC on the data.</p>\n<p>This exposes a padding oracle vulnerability: If the attacker has write access to the blob container bucket and can observe whether or not an endpoint with access to the key can decrypt a file (without observing the file contents that the endpoint learns in the process), they can reconstruct the plaintext with (on average) 128*length(plaintext) queries to the endpoint, by exploiting CBC's ability to manipulate the bytes of the next block and PKCS5 padding errors.</p>\n<h3 id=\"timeline\">Timeline</h3>\n<p><strong>Date reported</strong>: March 29 2022\n<strong>Date preview</strong>: June 16 2022\n<strong>Date GA</strong>: July 11 2022\n<strong>Date disclosed</strong>: July 17 2022</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-30187\">https://nvd.nist.gov/vuln/detail/CVE-2022-30187</a></li>\n<li><a href=\"https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2022-30187\">https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2022-30187</a></li>\n<li><a href=\"https://github.com/google/security-research/security/advisories/GHSA-6m8q-r22q-vfxh\">https://github.com/google/security-research/security/advisories/GHSA-6m8q-r22q-vfxh</a></li>\n<li><a href=\"https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-30187\">https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-30187</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-64x4-9hc6-r2h6\">https://github.com/advisories/GHSA-64x4-9hc6-r2h6</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-64x4-9hc6-r2h6",
            "title": "[azure-storage-queue] Microsoft: CBC Padding Oracle in Azure Blob Storage Encryption Library",
            "date_modified": "2024-05-23T17:12:44.000Z",
            "date_published": "2022-07-13T00:00:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-64x4-9hc6-r2h6"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>jupyter_scheduler</code> is missing an authentication check in Jupyter Server on an API endpoint (<code>GET /scheduler/runtime_environments</code>) which lists the names of the Conda environments on the server. In affected versions, <code>jupyter_scheduler</code> allows an unauthenticated user to obtain the list of Conda environment names on the server. This reveals any information that may be present in a Conda environment name.</p>\n<p>This issue does <strong>not</strong> allow an unauthenticated third party to read, modify, or enter the Conda environments present on the server where <code>jupyter_scheduler</code> is running. This issue only reveals the list of Conda environment names.</p>\n<p>Impacted versions: <code>&gt;=1.0.0,&lt;=1.1.5 ; ==1.2.0 ; &gt;=1.3.0,&lt;=1.8.1 ; &gt;=2.0.0,&lt;=2.5.1</code></p>\n<h3 id=\"patches\">Patches</h3>\n<ul>\n<li><code>jupyter-scheduler==1.1.6</code></li>\n<li><code>jupyter-scheduler==1.2.1</code></li>\n<li><code>jupyter-scheduler==1.8.2</code></li>\n<li><code>jupyter-scheduler==2.5.2</code></li>\n</ul>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>Server operators who are unable to upgrade can disable the <code>jupyter-scheduler</code> extension with:</p>\n<pre><code>jupyter server extension disable jupyter-scheduler\n</code></pre>\n<h3 id=\"references\">References</h3>\n<p>If you have any questions or comments about this advisory we ask that you contact AWS/Amazon Security via our vulnerability reporting page [1] or directly via email to <a href=\"mailto:aws-security@amazon.com\">aws-security@amazon.com</a>. Please do not create a public GitHub issue.</p>\n<p>[1] Vulnerability reporting page: <a href=\"https://aws.amazon.com/security/vulnerability-reporting\">https://aws.amazon.com/security/vulnerability-reporting</a></p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/security/advisories/GHSA-v9g2-g7j4-4jxc\">https://github.com/jupyter-server/jupyter-scheduler/security/advisories/GHSA-v9g2-g7j4-4jxc</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-28188\">https://nvd.nist.gov/vuln/detail/CVE-2024-28188</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter_server/pull/1392\">https://github.com/jupyter-server/jupyter_server/pull/1392</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/06435a2277bb2b8f441ec9cedafa474572b92c5d\">https://github.com/jupyter-server/jupyter-scheduler/commit/06435a2277bb2b8f441ec9cedafa474572b92c5d</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/a621b386397280cc8ee5a208dca4607cb71cdd65\">https://github.com/jupyter-server/jupyter-scheduler/commit/a621b386397280cc8ee5a208dca4607cb71cdd65</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/d428ac871909444e175ba421bf8ab4980d6ebf9f\">https://github.com/jupyter-server/jupyter-scheduler/commit/d428ac871909444e175ba421bf8ab4980d6ebf9f</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/f4137a779fdf0cc4a9688a42dd8c6e7ade60f044\">https://github.com/jupyter-server/jupyter-scheduler/commit/f4137a779fdf0cc4a9688a42dd8c6e7ade60f044</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v9g2-g7j4-4jxc\">https://github.com/advisories/GHSA-v9g2-g7j4-4jxc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v9g2-g7j4-4jxc",
            "title": "[jupyter-scheduler] jupyter-scheduler's endpoint is missing authentication",
            "date_modified": "2024-05-27T08:43:59.000Z",
            "date_published": "2024-05-23T14:00:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v9g2-g7j4-4jxc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>jupyter_scheduler</code> is missing an authentication check in Jupyter Server on an API endpoint (<code>GET /scheduler/runtime_environments</code>) which lists the names of the Conda environments on the server. In affected versions, <code>jupyter_scheduler</code> allows an unauthenticated user to obtain the list of Conda environment names on the server. This reveals any information that may be present in a Conda environment name.</p>\n<p>This issue does <strong>not</strong> allow an unauthenticated third party to read, modify, or enter the Conda environments present on the server where <code>jupyter_scheduler</code> is running. This issue only reveals the list of Conda environment names.</p>\n<p>Impacted versions: <code>&gt;=1.0.0,&lt;=1.1.5 ; ==1.2.0 ; &gt;=1.3.0,&lt;=1.8.1 ; &gt;=2.0.0,&lt;=2.5.1</code></p>\n<h3 id=\"patches\">Patches</h3>\n<ul>\n<li><code>jupyter-scheduler==1.1.6</code></li>\n<li><code>jupyter-scheduler==1.2.1</code></li>\n<li><code>jupyter-scheduler==1.8.2</code></li>\n<li><code>jupyter-scheduler==2.5.2</code></li>\n</ul>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>Server operators who are unable to upgrade can disable the <code>jupyter-scheduler</code> extension with:</p>\n<pre><code>jupyter server extension disable jupyter-scheduler\n</code></pre>\n<h3 id=\"references\">References</h3>\n<p>If you have any questions or comments about this advisory we ask that you contact AWS/Amazon Security via our vulnerability reporting page [1] or directly via email to <a href=\"mailto:aws-security@amazon.com\">aws-security@amazon.com</a>. Please do not create a public GitHub issue.</p>\n<p>[1] Vulnerability reporting page: <a href=\"https://aws.amazon.com/security/vulnerability-reporting\">https://aws.amazon.com/security/vulnerability-reporting</a></p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/security/advisories/GHSA-v9g2-g7j4-4jxc\">https://github.com/jupyter-server/jupyter-scheduler/security/advisories/GHSA-v9g2-g7j4-4jxc</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-28188\">https://nvd.nist.gov/vuln/detail/CVE-2024-28188</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter_server/pull/1392\">https://github.com/jupyter-server/jupyter_server/pull/1392</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/06435a2277bb2b8f441ec9cedafa474572b92c5d\">https://github.com/jupyter-server/jupyter-scheduler/commit/06435a2277bb2b8f441ec9cedafa474572b92c5d</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/a621b386397280cc8ee5a208dca4607cb71cdd65\">https://github.com/jupyter-server/jupyter-scheduler/commit/a621b386397280cc8ee5a208dca4607cb71cdd65</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/d428ac871909444e175ba421bf8ab4980d6ebf9f\">https://github.com/jupyter-server/jupyter-scheduler/commit/d428ac871909444e175ba421bf8ab4980d6ebf9f</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/f4137a779fdf0cc4a9688a42dd8c6e7ade60f044\">https://github.com/jupyter-server/jupyter-scheduler/commit/f4137a779fdf0cc4a9688a42dd8c6e7ade60f044</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v9g2-g7j4-4jxc\">https://github.com/advisories/GHSA-v9g2-g7j4-4jxc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v9g2-g7j4-4jxc",
            "title": "[jupyter-scheduler] jupyter-scheduler's endpoint is missing authentication",
            "date_modified": "2024-05-27T08:43:59.000Z",
            "date_published": "2024-05-23T14:00:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v9g2-g7j4-4jxc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>jupyter_scheduler</code> is missing an authentication check in Jupyter Server on an API endpoint (<code>GET /scheduler/runtime_environments</code>) which lists the names of the Conda environments on the server. In affected versions, <code>jupyter_scheduler</code> allows an unauthenticated user to obtain the list of Conda environment names on the server. This reveals any information that may be present in a Conda environment name.</p>\n<p>This issue does <strong>not</strong> allow an unauthenticated third party to read, modify, or enter the Conda environments present on the server where <code>jupyter_scheduler</code> is running. This issue only reveals the list of Conda environment names.</p>\n<p>Impacted versions: <code>&gt;=1.0.0,&lt;=1.1.5 ; ==1.2.0 ; &gt;=1.3.0,&lt;=1.8.1 ; &gt;=2.0.0,&lt;=2.5.1</code></p>\n<h3 id=\"patches\">Patches</h3>\n<ul>\n<li><code>jupyter-scheduler==1.1.6</code></li>\n<li><code>jupyter-scheduler==1.2.1</code></li>\n<li><code>jupyter-scheduler==1.8.2</code></li>\n<li><code>jupyter-scheduler==2.5.2</code></li>\n</ul>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>Server operators who are unable to upgrade can disable the <code>jupyter-scheduler</code> extension with:</p>\n<pre><code>jupyter server extension disable jupyter-scheduler\n</code></pre>\n<h3 id=\"references\">References</h3>\n<p>If you have any questions or comments about this advisory we ask that you contact AWS/Amazon Security via our vulnerability reporting page [1] or directly via email to <a href=\"mailto:aws-security@amazon.com\">aws-security@amazon.com</a>. Please do not create a public GitHub issue.</p>\n<p>[1] Vulnerability reporting page: <a href=\"https://aws.amazon.com/security/vulnerability-reporting\">https://aws.amazon.com/security/vulnerability-reporting</a></p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/security/advisories/GHSA-v9g2-g7j4-4jxc\">https://github.com/jupyter-server/jupyter-scheduler/security/advisories/GHSA-v9g2-g7j4-4jxc</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-28188\">https://nvd.nist.gov/vuln/detail/CVE-2024-28188</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter_server/pull/1392\">https://github.com/jupyter-server/jupyter_server/pull/1392</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/06435a2277bb2b8f441ec9cedafa474572b92c5d\">https://github.com/jupyter-server/jupyter-scheduler/commit/06435a2277bb2b8f441ec9cedafa474572b92c5d</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/a621b386397280cc8ee5a208dca4607cb71cdd65\">https://github.com/jupyter-server/jupyter-scheduler/commit/a621b386397280cc8ee5a208dca4607cb71cdd65</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/d428ac871909444e175ba421bf8ab4980d6ebf9f\">https://github.com/jupyter-server/jupyter-scheduler/commit/d428ac871909444e175ba421bf8ab4980d6ebf9f</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/f4137a779fdf0cc4a9688a42dd8c6e7ade60f044\">https://github.com/jupyter-server/jupyter-scheduler/commit/f4137a779fdf0cc4a9688a42dd8c6e7ade60f044</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v9g2-g7j4-4jxc\">https://github.com/advisories/GHSA-v9g2-g7j4-4jxc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v9g2-g7j4-4jxc",
            "title": "[jupyter-scheduler] jupyter-scheduler's endpoint is missing authentication",
            "date_modified": "2024-05-27T08:43:59.000Z",
            "date_published": "2024-05-23T14:00:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v9g2-g7j4-4jxc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>jupyter_scheduler</code> is missing an authentication check in Jupyter Server on an API endpoint (<code>GET /scheduler/runtime_environments</code>) which lists the names of the Conda environments on the server. In affected versions, <code>jupyter_scheduler</code> allows an unauthenticated user to obtain the list of Conda environment names on the server. This reveals any information that may be present in a Conda environment name.</p>\n<p>This issue does <strong>not</strong> allow an unauthenticated third party to read, modify, or enter the Conda environments present on the server where <code>jupyter_scheduler</code> is running. This issue only reveals the list of Conda environment names.</p>\n<p>Impacted versions: <code>&gt;=1.0.0,&lt;=1.1.5 ; ==1.2.0 ; &gt;=1.3.0,&lt;=1.8.1 ; &gt;=2.0.0,&lt;=2.5.1</code></p>\n<h3 id=\"patches\">Patches</h3>\n<ul>\n<li><code>jupyter-scheduler==1.1.6</code></li>\n<li><code>jupyter-scheduler==1.2.1</code></li>\n<li><code>jupyter-scheduler==1.8.2</code></li>\n<li><code>jupyter-scheduler==2.5.2</code></li>\n</ul>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>Server operators who are unable to upgrade can disable the <code>jupyter-scheduler</code> extension with:</p>\n<pre><code>jupyter server extension disable jupyter-scheduler\n</code></pre>\n<h3 id=\"references\">References</h3>\n<p>If you have any questions or comments about this advisory we ask that you contact AWS/Amazon Security via our vulnerability reporting page [1] or directly via email to <a href=\"mailto:aws-security@amazon.com\">aws-security@amazon.com</a>. Please do not create a public GitHub issue.</p>\n<p>[1] Vulnerability reporting page: <a href=\"https://aws.amazon.com/security/vulnerability-reporting\">https://aws.amazon.com/security/vulnerability-reporting</a></p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/security/advisories/GHSA-v9g2-g7j4-4jxc\">https://github.com/jupyter-server/jupyter-scheduler/security/advisories/GHSA-v9g2-g7j4-4jxc</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-28188\">https://nvd.nist.gov/vuln/detail/CVE-2024-28188</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter_server/pull/1392\">https://github.com/jupyter-server/jupyter_server/pull/1392</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/06435a2277bb2b8f441ec9cedafa474572b92c5d\">https://github.com/jupyter-server/jupyter-scheduler/commit/06435a2277bb2b8f441ec9cedafa474572b92c5d</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/a621b386397280cc8ee5a208dca4607cb71cdd65\">https://github.com/jupyter-server/jupyter-scheduler/commit/a621b386397280cc8ee5a208dca4607cb71cdd65</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/d428ac871909444e175ba421bf8ab4980d6ebf9f\">https://github.com/jupyter-server/jupyter-scheduler/commit/d428ac871909444e175ba421bf8ab4980d6ebf9f</a></li>\n<li><a href=\"https://github.com/jupyter-server/jupyter-scheduler/commit/f4137a779fdf0cc4a9688a42dd8c6e7ade60f044\">https://github.com/jupyter-server/jupyter-scheduler/commit/f4137a779fdf0cc4a9688a42dd8c6e7ade60f044</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v9g2-g7j4-4jxc\">https://github.com/advisories/GHSA-v9g2-g7j4-4jxc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v9g2-g7j4-4jxc",
            "title": "[jupyter-scheduler] jupyter-scheduler's endpoint is missing authentication",
            "date_modified": "2024-05-27T08:43:59.000Z",
            "date_published": "2024-05-23T14:00:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v9g2-g7j4-4jxc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>NASA AIT-Core v2.5.2 was discovered to use unencrypted channels to exchange data over the network, allowing attackers to execute a man-in-the-middle attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-35061\">https://nvd.nist.gov/vuln/detail/CVE-2024-35061</a></li>\n<li><a href=\"https://www.linkedin.com/pulse/remote-code-execution-via-man-in-the-middle-more-ujkze\">https://www.linkedin.com/pulse/remote-code-execution-via-man-in-the-middle-more-ujkze</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qv6x-53jj-vw59\">https://github.com/advisories/GHSA-qv6x-53jj-vw59</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qv6x-53jj-vw59",
            "title": "[ait-core] NASA AIT-Core uses unencrypted channels to exchange data over the network",
            "date_modified": "2024-05-22T19:28:59.000Z",
            "date_published": "2024-05-21T21:30:27.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qv6x-53jj-vw59"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Algorithmic complexity vulnerability in the forms library in Django 1.0 before 1.0.4 and 1.1 before 1.1.1 allows remote attackers to cause a denial of service (CPU consumption) via a crafted (1) EmailField (email address) or (2) URLField (URL) that triggers a large amount of backtracking in a regular expression.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2009-3695\">https://nvd.nist.gov/vuln/detail/CVE-2009-3695</a></li>\n<li><a href=\"https://exchange.xforce.ibmcloud.com/vulnerabilities/53727\">https://exchange.xforce.ibmcloud.com/vulnerabilities/53727</a></li>\n<li><a href=\"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457\">http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457</a></li>\n<li><a href=\"http://www.debian.org/security/2009/dsa-1905\">http://www.debian.org/security/2009/dsa-1905</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2009/10/13/6\">http://www.openwall.com/lists/oss-security/2009/10/13/6</a></li>\n<li><a href=\"https://web.archive.org/web/20200228171918/http://www.securityfocus.com/bid/36655\">https://web.archive.org/web/20200228171918/http://www.securityfocus.com/bid/36655</a></li>\n<li><a href=\"https://github.com/django/django/commit/594a28a9044120bed58671dde8a805c9e0f6c79a\">https://github.com/django/django/commit/594a28a9044120bed58671dde8a805c9e0f6c79a</a></li>\n<li><a href=\"https://github.com/django/django/commit/e3e992e18b368fcd56aabafc1b5bf80a6e11b495\">https://github.com/django/django/commit/e3e992e18b368fcd56aabafc1b5bf80a6e11b495</a></li>\n<li><a href=\"http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51\">http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51</a></li>\n<li><a href=\"http://www.djangoproject.com/weblog/2009/oct/09/security\">http://www.djangoproject.com/weblog/2009/oct/09/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p6m5-h7pp-v2x5\">https://github.com/advisories/GHSA-p6m5-h7pp-v2x5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p6m5-h7pp-v2x5",
            "title": "[Django] Django Regex Algorithmic Complexity Causes Denial of Service",
            "date_modified": "2024-05-22T19:06:37.000Z",
            "date_published": "2022-05-02T03:47:43.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p6m5-h7pp-v2x5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Algorithmic complexity vulnerability in the forms library in Django 1.0 before 1.0.4 and 1.1 before 1.1.1 allows remote attackers to cause a denial of service (CPU consumption) via a crafted (1) EmailField (email address) or (2) URLField (URL) that triggers a large amount of backtracking in a regular expression.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2009-3695\">https://nvd.nist.gov/vuln/detail/CVE-2009-3695</a></li>\n<li><a href=\"https://exchange.xforce.ibmcloud.com/vulnerabilities/53727\">https://exchange.xforce.ibmcloud.com/vulnerabilities/53727</a></li>\n<li><a href=\"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457\">http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457</a></li>\n<li><a href=\"http://www.debian.org/security/2009/dsa-1905\">http://www.debian.org/security/2009/dsa-1905</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2009/10/13/6\">http://www.openwall.com/lists/oss-security/2009/10/13/6</a></li>\n<li><a href=\"https://web.archive.org/web/20200228171918/http://www.securityfocus.com/bid/36655\">https://web.archive.org/web/20200228171918/http://www.securityfocus.com/bid/36655</a></li>\n<li><a href=\"https://github.com/django/django/commit/594a28a9044120bed58671dde8a805c9e0f6c79a\">https://github.com/django/django/commit/594a28a9044120bed58671dde8a805c9e0f6c79a</a></li>\n<li><a href=\"https://github.com/django/django/commit/e3e992e18b368fcd56aabafc1b5bf80a6e11b495\">https://github.com/django/django/commit/e3e992e18b368fcd56aabafc1b5bf80a6e11b495</a></li>\n<li><a href=\"http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51\">http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51</a></li>\n<li><a href=\"http://www.djangoproject.com/weblog/2009/oct/09/security\">http://www.djangoproject.com/weblog/2009/oct/09/security</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p6m5-h7pp-v2x5\">https://github.com/advisories/GHSA-p6m5-h7pp-v2x5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p6m5-h7pp-v2x5",
            "title": "[Django] Django Regex Algorithmic Complexity Causes Denial of Service",
            "date_modified": "2024-05-22T19:06:37.000Z",
            "date_published": "2022-05-02T03:47:43.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p6m5-h7pp-v2x5"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}