{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>Denial of service (DoS) vulnerability in Nicotine+ starting with version 3.0.3 and prior to version 3.2.1 allows a user with a modified Soulseek client to crash Nicotine+ by sending a file download request with a file path containing a null character.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-45848\">https://nvd.nist.gov/vuln/detail/CVE-2021-45848</a></li>\n<li><a href=\"https://github.com/nicotine-plus/nicotine-plus/issues/1777\">https://github.com/nicotine-plus/nicotine-plus/issues/1777</a></li>\n<li><a href=\"https://github.com/nicotine-plus/nicotine-plus/commit/0e3e2fac27a518f0a84330f1ddf1193424522045\">https://github.com/nicotine-plus/nicotine-plus/commit/0e3e2fac27a518f0a84330f1ddf1193424522045</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWYV53KERFH2EC4XI2IVVQFTV75E5XM6/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWYV53KERFH2EC4XI2IVVQFTV75E5XM6/</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202210-20\">https://security.gentoo.org/glsa/202210-20</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p4v2-r99v-wjc2\">https://github.com/advisories/GHSA-p4v2-r99v-wjc2</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p4v2-r99v-wjc2",
            "title": "[nicotine-plus] Nicotine+ DoS on Null Character in Download Request",
            "date_modified": "2023-09-05T19:58:24.000Z",
            "date_published": "2022-03-16T00:00:38.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p4v2-r99v-wjc2"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-45115\">https://nvd.nist.gov/vuln/detail/CVE-2021-45115</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.0/releases/security/\">https://docs.djangoproject.com/en/4.0/releases/security/</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/\">https://www.djangoproject.com/weblog/2022/jan/04/security-releases/</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20220121-0005/\">https://security.netapp.com/advisory/ntap-20220121-0005/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-53qw-q765-4fww\">https://github.com/advisories/GHSA-53qw-q765-4fww</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-53qw-q765-4fww",
            "title": "[Django] Denial-of-service in Django",
            "date_modified": "2023-09-05T19:51:28.000Z",
            "date_published": "2022-01-12T19:20:53.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-53qw-q765-4fww"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-45115\">https://nvd.nist.gov/vuln/detail/CVE-2021-45115</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.0/releases/security/\">https://docs.djangoproject.com/en/4.0/releases/security/</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/\">https://www.djangoproject.com/weblog/2022/jan/04/security-releases/</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20220121-0005/\">https://security.netapp.com/advisory/ntap-20220121-0005/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-53qw-q765-4fww\">https://github.com/advisories/GHSA-53qw-q765-4fww</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-53qw-q765-4fww",
            "title": "[Django] Denial-of-service in Django",
            "date_modified": "2023-09-05T19:51:28.000Z",
            "date_published": "2022-01-12T19:20:53.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-53qw-q765-4fww"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-45115\">https://nvd.nist.gov/vuln/detail/CVE-2021-45115</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.0/releases/security/\">https://docs.djangoproject.com/en/4.0/releases/security/</a></li>\n<li><a href=\"https://groups.google.com/forum/#!forum/django-announce\">https://groups.google.com/forum/#!forum/django-announce</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/\">https://www.djangoproject.com/weblog/2022/jan/04/security-releases/</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20220121-0005/\">https://security.netapp.com/advisory/ntap-20220121-0005/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-53qw-q765-4fww\">https://github.com/advisories/GHSA-53qw-q765-4fww</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-53qw-q765-4fww",
            "title": "[Django] Denial-of-service in Django",
            "date_modified": "2023-09-05T19:51:28.000Z",
            "date_published": "2022-01-12T19:20:53.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-53qw-q765-4fww"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>utils.http.is_safe_url function</code> in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by <code>http://mysite.example.com\\@attacker.com</code>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-2512\">https://nvd.nist.gov/vuln/detail/CVE-2016-2512</a></li>\n<li><a href=\"https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0\">https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2016/mar/01/security-releases/\">https://www.djangoproject.com/weblog/2016/mar/01/security-releases/</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0502.html\">http://rhn.redhat.com/errata/RHSA-2016-0502.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0504.html\">http://rhn.redhat.com/errata/RHSA-2016-0504.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0505.html\">http://rhn.redhat.com/errata/RHSA-2016-0505.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0506.html\">http://rhn.redhat.com/errata/RHSA-2016-0506.html</a></li>\n<li><a href=\"http://www.debian.org/security/2016/dsa-3544\">http://www.debian.org/security/2016/dsa-3544</a></li>\n<li><a href=\"http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html\">http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2915-1\">http://www.ubuntu.com/usn/USN-2915-1</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2915-2\">http://www.ubuntu.com/usn/USN-2915-2</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2915-3\">http://www.ubuntu.com/usn/USN-2915-3</a></li>\n<li><a href=\"https://web.archive.org/web/20210123090815/http://www.securityfocus.com/bid/83879\">https://web.archive.org/web/20210123090815/http://www.securityfocus.com/bid/83879</a></li>\n<li><a href=\"https://web.archive.org/web/20210413200202/http://www.securitytracker.com/id/1035152\">https://web.archive.org/web/20210413200202/http://www.securitytracker.com/id/1035152</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pw27-w7w4-9qc7\">https://github.com/advisories/GHSA-pw27-w7w4-9qc7</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pw27-w7w4-9qc7",
            "title": "[django] Django XSS Vulnerability",
            "date_modified": "2023-09-05T19:47:02.000Z",
            "date_published": "2022-05-17T01:09:58.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pw27-w7w4-9qc7"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>utils.http.is_safe_url function</code> in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by <code>http://mysite.example.com\\@attacker.com</code>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-2512\">https://nvd.nist.gov/vuln/detail/CVE-2016-2512</a></li>\n<li><a href=\"https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0\">https://github.com/django/django/commit/c5544d289233f501917e25970c03ed444abbd4f0</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2016/mar/01/security-releases/\">https://www.djangoproject.com/weblog/2016/mar/01/security-releases/</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0502.html\">http://rhn.redhat.com/errata/RHSA-2016-0502.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0504.html\">http://rhn.redhat.com/errata/RHSA-2016-0504.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0505.html\">http://rhn.redhat.com/errata/RHSA-2016-0505.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2016-0506.html\">http://rhn.redhat.com/errata/RHSA-2016-0506.html</a></li>\n<li><a href=\"http://www.debian.org/security/2016/dsa-3544\">http://www.debian.org/security/2016/dsa-3544</a></li>\n<li><a href=\"http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html\">http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2915-1\">http://www.ubuntu.com/usn/USN-2915-1</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2915-2\">http://www.ubuntu.com/usn/USN-2915-2</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2915-3\">http://www.ubuntu.com/usn/USN-2915-3</a></li>\n<li><a href=\"https://web.archive.org/web/20210123090815/http://www.securityfocus.com/bid/83879\">https://web.archive.org/web/20210123090815/http://www.securityfocus.com/bid/83879</a></li>\n<li><a href=\"https://web.archive.org/web/20210413200202/http://www.securitytracker.com/id/1035152\">https://web.archive.org/web/20210413200202/http://www.securitytracker.com/id/1035152</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pw27-w7w4-9qc7\">https://github.com/advisories/GHSA-pw27-w7w4-9qc7</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pw27-w7w4-9qc7",
            "title": "[django] Django XSS Vulnerability",
            "date_modified": "2023-09-05T19:47:02.000Z",
            "date_published": "2022-05-17T01:09:58.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pw27-w7w4-9qc7"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Matrix Synapse before 0.28.1 is prone to a denial of service flaw where malicious events injected with depth = 2<sup>63</sup> - 1 render rooms unusable, related to <code>federation/federation_base.py</code> and <code>handlers/message.py</code>, as exploited in the wild in April 2018.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-10657\">https://nvd.nist.gov/vuln/detail/CVE-2018-10657</a></li>\n<li><a href=\"https://github.com/matrix-org/synapse/commit/33f469ba19586bbafa0cf2c7d7c35463bdab87eb\">https://github.com/matrix-org/synapse/commit/33f469ba19586bbafa0cf2c7d7c35463bdab87eb</a></li>\n<li><a href=\"https://matrix.org/blog/2018/05/01/security-update-synapse-0-28-1/\">https://matrix.org/blog/2018/05/01/security-update-synapse-0-28-1/</a></li>\n<li><a href=\"https://docs.google.com/document/d/1I3fi2S-XnpO45qrpCsowZv8P8dHcNZ4fsBsbOW7KABI/edit#heading=h.fj95ykuss7s1\">https://docs.google.com/document/d/1I3fi2S-XnpO45qrpCsowZv8P8dHcNZ4fsBsbOW7KABI/edit#heading=h.fj95ykuss7s1</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vmcc-4p4x-x7wg\">https://github.com/advisories/GHSA-vmcc-4p4x-x7wg</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vmcc-4p4x-x7wg",
            "title": "[matrix-synapse] Matrix Synapse DoS",
            "date_modified": "2023-09-05T19:27:07.000Z",
            "date_published": "2022-05-14T03:20:03.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vmcc-4p4x-x7wg"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Synapse before 0.31.2, unauthorised users can hijack rooms when there is no <code>m.room.power_levels</code> event in force.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-12423\">https://nvd.nist.gov/vuln/detail/CVE-2018-12423</a></li>\n<li><a href=\"https://github.com/matrix-org/matrix-doc/issues/1304\">https://github.com/matrix-org/matrix-doc/issues/1304</a></li>\n<li><a href=\"https://bugs.debian.org/901549\">https://bugs.debian.org/901549</a></li>\n<li><a href=\"https://matrix.org/blog/2018/06/14/security-update-synapse-0-31-2/\">https://matrix.org/blog/2018/06/14/security-update-synapse-0-31-2/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-ch5v-fhg8-7gv9\">https://github.com/advisories/GHSA-ch5v-fhg8-7gv9</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-ch5v-fhg8-7gv9",
            "title": "[matrix-synapse] Matrix Synapse Authorization Error",
            "date_modified": "2023-09-05T19:14:20.000Z",
            "date_published": "2022-05-13T01:49:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-ch5v-fhg8-7gv9"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Jupyter Notebook before 5.7.2 allows XSS via a crafted directory name because notebook/static/tree/js/notebooklist.js handles certain URLs unsafely.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-19352\">https://nvd.nist.gov/vuln/detail/CVE-2018-19352</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/commit/288b73e1edbf527740e273fcc69b889460871648\">https://github.com/jupyter/notebook/commit/288b73e1edbf527740e273fcc69b889460871648</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3p4q-x8f3-p7vq\">https://github.com/advisories/GHSA-3p4q-x8f3-p7vq</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst\">https://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst</a></li>\n<li><a href=\"https://pypi.org/project/notebook/#history\">https://pypi.org/project/notebook/#history</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3p4q-x8f3-p7vq",
            "title": "[notebook] Jupyter Notebook XSS via directory name",
            "date_modified": "2023-09-05T19:12:37.000Z",
            "date_published": "2018-11-21T22:19:22.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3p4q-x8f3-p7vq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in <code>django.views.defaults.page_not_found()</code>, leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-3498\">https://nvd.nist.gov/vuln/detail/CVE-2019-3498</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security/\">https://docs.djangoproject.com/en/dev/releases/security/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-337x-4q8g-prc5\">https://github.com/advisories/GHSA-337x-4q8g-prc5</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ\">https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html\">https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/</a></li>\n<li><a href=\"https://usn.ubuntu.com/3851-1/\">https://usn.ubuntu.com/3851-1/</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4363\">https://www.debian.org/security/2019/dsa-4363</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/jan/04/security-releases/\">https://www.djangoproject.com/weblog/2019/jan/04/security-releases/</a></li>\n<li><a href=\"https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453\">https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5",
            "title": "[django] Improper Input Validation in Django",
            "date_modified": "2023-09-05T18:43:36.000Z",
            "date_published": "2019-01-14T16:20:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in <code>django.views.defaults.page_not_found()</code>, leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-3498\">https://nvd.nist.gov/vuln/detail/CVE-2019-3498</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security/\">https://docs.djangoproject.com/en/dev/releases/security/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-337x-4q8g-prc5\">https://github.com/advisories/GHSA-337x-4q8g-prc5</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ\">https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html\">https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/</a></li>\n<li><a href=\"https://usn.ubuntu.com/3851-1/\">https://usn.ubuntu.com/3851-1/</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4363\">https://www.debian.org/security/2019/dsa-4363</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/jan/04/security-releases/\">https://www.djangoproject.com/weblog/2019/jan/04/security-releases/</a></li>\n<li><a href=\"https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453\">https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5",
            "title": "[django] Improper Input Validation in Django",
            "date_modified": "2023-09-05T18:43:36.000Z",
            "date_published": "2019-01-14T16:20:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in <code>django.views.defaults.page_not_found()</code>, leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-3498\">https://nvd.nist.gov/vuln/detail/CVE-2019-3498</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security/\">https://docs.djangoproject.com/en/dev/releases/security/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-337x-4q8g-prc5\">https://github.com/advisories/GHSA-337x-4q8g-prc5</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ\">https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html\">https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/</a></li>\n<li><a href=\"https://usn.ubuntu.com/3851-1/\">https://usn.ubuntu.com/3851-1/</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4363\">https://www.debian.org/security/2019/dsa-4363</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/jan/04/security-releases/\">https://www.djangoproject.com/weblog/2019/jan/04/security-releases/</a></li>\n<li><a href=\"https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453\">https://web.archive.org/web/20200227094237/http://www.securityfocus.com/bid/106453</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5",
            "title": "[django] Improper Input Validation in Django",
            "date_modified": "2023-09-05T18:43:36.000Z",
            "date_published": "2019-01-14T16:20:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-337x-4q8g-prc5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Jupyter Notebook before 5.7.1 allows XSS via an untrusted notebook because nbconvert responses are considered to have the same origin as the notebook server. In other words, nbconvert endpoints can execute JavaScript with access to the server API. In notebook/nbconvert/handlers.py, NbconvertFileHandler and NbconvertPostHandler do not set a Content Security Policy to prevent this.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-19351\">https://nvd.nist.gov/vuln/detail/CVE-2018-19351</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/commit/107a89fce5f413fb5728c1c5d2c7788e1fb17491\">https://github.com/jupyter/notebook/commit/107a89fce5f413fb5728c1c5d2c7788e1fb17491</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-49qr-xh3w-h436\">https://github.com/advisories/GHSA-49qr-xh3w-h436</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst\">https://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/jupyter/hWzu2BSsplY\">https://groups.google.com/forum/#!topic/jupyter/hWzu2BSsplY</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2020/11/msg00033.html\">https://lists.debian.org/debian-lts-announce/2020/11/msg00033.html</a></li>\n<li><a href=\"https://pypi.org/project/notebook/#history\">https://pypi.org/project/notebook/#history</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-49qr-xh3w-h436",
            "title": "[notebook] Jupyter Notebook XSS via untrusted notebooks",
            "date_modified": "2023-09-05T18:42:36.000Z",
            "date_published": "2018-11-21T22:15:47.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-49qr-xh3w-h436"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p><code>django.middleware.common.CommonMiddleware</code> in Django 1.11.x before 1.11.15 and 2.0.x before 2.0.8 has an Open Redirect.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-14574\">https://nvd.nist.gov/vuln/detail/CVE-2018-14574</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:0265\">https://access.redhat.com/errata/RHSA-2019:0265</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5hg3-6c2f-f3wr\">https://github.com/advisories/GHSA-5hg3-6c2f-f3wr</a></li>\n<li><a href=\"https://usn.ubuntu.com/3726-1/\">https://usn.ubuntu.com/3726-1/</a></li>\n<li><a href=\"https://www.debian.org/security/2018/dsa-4264\">https://www.debian.org/security/2018/dsa-4264</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2018/aug/01/security-releases/\">https://www.djangoproject.com/weblog/2018/aug/01/security-releases/</a></li>\n<li><a href=\"https://web.archive.org/web/20190901075632/http://www.securitytracker.com/id/1041403\">https://web.archive.org/web/20190901075632/http://www.securitytracker.com/id/1041403</a></li>\n<li><a href=\"https://web.archive.org/web/20200227115315/http://www.securityfocus.com/bid/104970\">https://web.archive.org/web/20200227115315/http://www.securityfocus.com/bid/104970</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5hg3-6c2f-f3wr",
            "title": "[django] Django open redirect",
            "date_modified": "2023-09-05T18:41:50.000Z",
            "date_published": "2018-10-04T21:58:46.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5hg3-6c2f-f3wr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p><code>django.middleware.common.CommonMiddleware</code> in Django 1.11.x before 1.11.15 and 2.0.x before 2.0.8 has an Open Redirect.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-14574\">https://nvd.nist.gov/vuln/detail/CVE-2018-14574</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:0265\">https://access.redhat.com/errata/RHSA-2019:0265</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5hg3-6c2f-f3wr\">https://github.com/advisories/GHSA-5hg3-6c2f-f3wr</a></li>\n<li><a href=\"https://usn.ubuntu.com/3726-1/\">https://usn.ubuntu.com/3726-1/</a></li>\n<li><a href=\"https://www.debian.org/security/2018/dsa-4264\">https://www.debian.org/security/2018/dsa-4264</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2018/aug/01/security-releases/\">https://www.djangoproject.com/weblog/2018/aug/01/security-releases/</a></li>\n<li><a href=\"https://web.archive.org/web/20190901075632/http://www.securitytracker.com/id/1041403\">https://web.archive.org/web/20190901075632/http://www.securitytracker.com/id/1041403</a></li>\n<li><a href=\"https://web.archive.org/web/20200227115315/http://www.securityfocus.com/bid/104970\">https://web.archive.org/web/20200227115315/http://www.securityfocus.com/bid/104970</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5hg3-6c2f-f3wr",
            "title": "[django] Django open redirect",
            "date_modified": "2023-09-05T18:41:50.000Z",
            "date_published": "2018-10-04T21:58:46.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5hg3-6c2f-f3wr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>Serialize.deserialize()</code> method in CoAPthon 3.1, 4.0.0, 4.0.1, and 4.0.2 mishandles certain exceptions, leading to a denial of service in applications that use this library (e.g., the standard CoAP server, CoAP client, CoAP reverse proxy, example collect CoAP server and client) when they receive crafted CoAP messages.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-12680\">https://nvd.nist.gov/vuln/detail/CVE-2018-12680</a></li>\n<li><a href=\"https://github.com/Tanganelli/CoAPthon/issues/135\">https://github.com/Tanganelli/CoAPthon/issues/135</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5xc6-fpc7-4qvg\">https://github.com/advisories/GHSA-5xc6-fpc7-4qvg</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5xc6-fpc7-4qvg",
            "title": "[CoAPthon] CoAPthon DoS due to Exceptions",
            "date_modified": "2023-09-05T18:40:25.000Z",
            "date_published": "2019-04-08T15:19:01.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5xc6-fpc7-4qvg"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django 2.1 before 2.1.2, in which unprivileged users can read the password hashes of arbitrary accounts. The read-only password widget used by the Django Admin to display an obfuscated password hash was bypassed if a user has only the \"view\" permission (new in Django 2.1), resulting in display of the entire password hash to those users. This may result in a vulnerability for sites with legacy user accounts using insecure hashes.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-16984\">https://nvd.nist.gov/vuln/detail/CVE-2018-16984</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6mx3-3vqg-hpp2\">https://github.com/advisories/GHSA-6mx3-3vqg-hpp2</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190502-0009/\">https://security.netapp.com/advisory/ntap-20190502-0009/</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2018/oct/01/security-release/\">https://www.djangoproject.com/weblog/2018/oct/01/security-release/</a></li>\n<li><a href=\"https://web.archive.org/web/20200517123022/http://www.securitytracker.com/id/1041749\">https://web.archive.org/web/20200517123022/http://www.securitytracker.com/id/1041749</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6mx3-3vqg-hpp2",
            "title": "[django] Django allows unprivileged users to read the password hashes of arbitrary accounts",
            "date_modified": "2023-09-05T18:37:45.000Z",
            "date_published": "2018-10-03T20:07:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6mx3-3vqg-hpp2"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the <code>ssl_context</code>, <code>ca_certs</code>, or <code>ca_certs_dir</code> argument.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-11324\">https://nvd.nist.gov/vuln/detail/CVE-2019-11324</a></li>\n<li><a href=\"https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4\">https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4</a></li>\n<li><a href=\"https://pypi.org/project/urllib3/1.24.2/\">https://pypi.org/project/urllib3/1.24.2/</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:3335\">https://access.redhat.com/errata/RHSA-2019:3335</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:3590\">https://access.redhat.com/errata/RHSA-2019:3590</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html\">https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/</a></li>\n<li><a href=\"https://usn.ubuntu.com/3990-1/\">https://usn.ubuntu.com/3990-1/</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html\">http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html\">http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2019/04/19/1\">http://www.openwall.com/lists/oss-security/2019/04/19/1</a></li>\n<li><a href=\"https://github.com/urllib3/urllib3/commit/1efadf43dc63317cd9eaa3e0fdb9e05ab07254b1\">https://github.com/urllib3/urllib3/commit/1efadf43dc63317cd9eaa3e0fdb9e05ab07254b1</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mh33-7rrq-662w\">https://github.com/advisories/GHSA-mh33-7rrq-662w</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mh33-7rrq-662w",
            "title": "[urllib3] Improper Certificate Validation in urllib3",
            "date_modified": "2023-09-05T18:28:04.000Z",
            "date_published": "2019-04-19T16:55:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mh33-7rrq-662w"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>There is a cross-site scripting vulnerability in django-epiceditor 0.2.3 via crafted content in a form field.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-6591\">https://nvd.nist.gov/vuln/detail/CVE-2017-6591</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xp5m-4c9f-498q\">https://github.com/advisories/GHSA-xp5m-4c9f-498q</a></li>\n<li><a href=\"https://web.archive.org/web/20170706013108/http://www.morningchen.com/2017/03/09/Cross-site-scripting-vulnerability-in-django-epiceditor/\">https://web.archive.org/web/20170706013108/http://www.morningchen.com/2017/03/09/Cross-site-scripting-vulnerability-in-django-epiceditor/</a></li>\n<li><a href=\"https://web.archive.org/web/20200227183140/http://www.securityfocus.com/bid/96946\">https://web.archive.org/web/20200227183140/http://www.securityfocus.com/bid/96946</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xp5m-4c9f-498q",
            "title": "[django-epiceditor] django-epiceditor vulnerable to XSS in form field",
            "date_modified": "2023-09-05T18:25:19.000Z",
            "date_published": "2018-07-13T15:17:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xp5m-4c9f-498q"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Jupyter Notebook before 5.7.8, an open redirect can occur via an empty netloc. This issue exists because of an incomplete fix for CVE-2019-10255.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-10856\">https://nvd.nist.gov/vuln/detail/CVE-2019-10856</a></li>\n<li><a href=\"https://blog.jupyter.org/open-redirect-vulnerability-in-jupyter-jupyterhub-adf43583f1e4\">https://blog.jupyter.org/open-redirect-vulnerability-in-jupyter-jupyterhub-adf43583f1e4</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rcx2-m7jp-p9wj\">https://github.com/advisories/GHSA-rcx2-m7jp-p9wj</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/compare/16cf97c...b8e30ea\">https://github.com/jupyter/notebook/compare/16cf97c...b8e30ea</a></li>\n<li><a href=\"https://github.com/jupyter/notebook/commit/979e0bd15e794ceb00cc63737fcd5fd9addc4a99\">https://github.com/jupyter/notebook/commit/979e0bd15e794ceb00cc63737fcd5fd9addc4a99</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rcx2-m7jp-p9wj",
            "title": "[notebook] Jupyter Notebook open redirect vulnerability",
            "date_modified": "2023-09-05T18:21:39.000Z",
            "date_published": "2019-04-09T19:47:27.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rcx2-m7jp-p9wj"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}